/*
MX Platform API

Testing MerchantsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mxplatformgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mxenabled/mx-platform-go"
)

func Test_mxplatformgo_MerchantsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MerchantsAPIService ListMerchants", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantsAPI.ListMerchants(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantsAPIService ReadMerchant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var merchantGuid string

		resp, httpRes, err := apiClient.MerchantsAPI.ReadMerchant(context.Background(), merchantGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantsAPIService ReadMerchantLocation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var merchantLocationGuid string

		resp, httpRes, err := apiClient.MerchantsAPI.ReadMerchantLocation(context.Background(), merchantLocationGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
