/*
MX Platform API

Testing TaggingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mxplatformgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mxenabled/mx-platform-go"
)

func Test_mxplatformgo_TaggingsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TaggingsAPIService CreateTagging", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userGuid string

		resp, httpRes, err := apiClient.TaggingsAPI.CreateTagging(context.Background(), userGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaggingsAPIService DeleteTagging", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var taggingGuid string
		var userGuid string

		httpRes, err := apiClient.TaggingsAPI.DeleteTagging(context.Background(), taggingGuid, userGuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaggingsAPIService ListTaggings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var userGuid string

		resp, httpRes, err := apiClient.TaggingsAPI.ListTaggings(context.Background(), userGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaggingsAPIService ReadTagging", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var taggingGuid string
		var userGuid string

		resp, httpRes, err := apiClient.TaggingsAPI.ReadTagging(context.Background(), taggingGuid, userGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TaggingsAPIService UpdateTagging", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var taggingGuid string
		var userGuid string

		resp, httpRes, err := apiClient.TaggingsAPI.UpdateTagging(context.Background(), taggingGuid, userGuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
