/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the PaymentProcessorAuthorizationCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentProcessorAuthorizationCodeResponse{}

// PaymentProcessorAuthorizationCodeResponse struct for PaymentProcessorAuthorizationCodeResponse
type PaymentProcessorAuthorizationCodeResponse struct {
	AuthorizationCode NullableString `json:"authorization_code,omitempty"`
}

// NewPaymentProcessorAuthorizationCodeResponse instantiates a new PaymentProcessorAuthorizationCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentProcessorAuthorizationCodeResponse() *PaymentProcessorAuthorizationCodeResponse {
	this := PaymentProcessorAuthorizationCodeResponse{}
	return &this
}

// NewPaymentProcessorAuthorizationCodeResponseWithDefaults instantiates a new PaymentProcessorAuthorizationCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentProcessorAuthorizationCodeResponseWithDefaults() *PaymentProcessorAuthorizationCodeResponse {
	this := PaymentProcessorAuthorizationCodeResponse{}
	return &this
}

// GetAuthorizationCode returns the AuthorizationCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentProcessorAuthorizationCodeResponse) GetAuthorizationCode() string {
	if o == nil || IsNil(o.AuthorizationCode.Get()) {
		var ret string
		return ret
	}
	return *o.AuthorizationCode.Get()
}

// GetAuthorizationCodeOk returns a tuple with the AuthorizationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentProcessorAuthorizationCodeResponse) GetAuthorizationCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthorizationCode.Get(), o.AuthorizationCode.IsSet()
}

// HasAuthorizationCode returns a boolean if a field has been set.
func (o *PaymentProcessorAuthorizationCodeResponse) HasAuthorizationCode() bool {
	if o != nil && o.AuthorizationCode.IsSet() {
		return true
	}

	return false
}

// SetAuthorizationCode gets a reference to the given NullableString and assigns it to the AuthorizationCode field.
func (o *PaymentProcessorAuthorizationCodeResponse) SetAuthorizationCode(v string) {
	o.AuthorizationCode.Set(&v)
}
// SetAuthorizationCodeNil sets the value for AuthorizationCode to be an explicit nil
func (o *PaymentProcessorAuthorizationCodeResponse) SetAuthorizationCodeNil() {
	o.AuthorizationCode.Set(nil)
}

// UnsetAuthorizationCode ensures that no value is present for AuthorizationCode, not even an explicit nil
func (o *PaymentProcessorAuthorizationCodeResponse) UnsetAuthorizationCode() {
	o.AuthorizationCode.Unset()
}

func (o PaymentProcessorAuthorizationCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentProcessorAuthorizationCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AuthorizationCode.IsSet() {
		toSerialize["authorization_code"] = o.AuthorizationCode.Get()
	}
	return toSerialize, nil
}

type NullablePaymentProcessorAuthorizationCodeResponse struct {
	value *PaymentProcessorAuthorizationCodeResponse
	isSet bool
}

func (v NullablePaymentProcessorAuthorizationCodeResponse) Get() *PaymentProcessorAuthorizationCodeResponse {
	return v.value
}

func (v *NullablePaymentProcessorAuthorizationCodeResponse) Set(val *PaymentProcessorAuthorizationCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentProcessorAuthorizationCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentProcessorAuthorizationCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentProcessorAuthorizationCodeResponse(val *PaymentProcessorAuthorizationCodeResponse) *NullablePaymentProcessorAuthorizationCodeResponse {
	return &NullablePaymentProcessorAuthorizationCodeResponse{value: val, isSet: true}
}

func (v NullablePaymentProcessorAuthorizationCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentProcessorAuthorizationCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


