/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the MonthlyCashFlowProfileRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonthlyCashFlowProfileRequestBody{}

// MonthlyCashFlowProfileRequestBody struct for MonthlyCashFlowProfileRequestBody
type MonthlyCashFlowProfileRequestBody struct {
	Institution *MonthlyCashFlowProfileRequest `json:"institution,omitempty"`
}

// NewMonthlyCashFlowProfileRequestBody instantiates a new MonthlyCashFlowProfileRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonthlyCashFlowProfileRequestBody() *MonthlyCashFlowProfileRequestBody {
	this := MonthlyCashFlowProfileRequestBody{}
	return &this
}

// NewMonthlyCashFlowProfileRequestBodyWithDefaults instantiates a new MonthlyCashFlowProfileRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonthlyCashFlowProfileRequestBodyWithDefaults() *MonthlyCashFlowProfileRequestBody {
	this := MonthlyCashFlowProfileRequestBody{}
	return &this
}

// GetInstitution returns the Institution field value if set, zero value otherwise.
func (o *MonthlyCashFlowProfileRequestBody) GetInstitution() MonthlyCashFlowProfileRequest {
	if o == nil || IsNil(o.Institution) {
		var ret MonthlyCashFlowProfileRequest
		return ret
	}
	return *o.Institution
}

// GetInstitutionOk returns a tuple with the Institution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonthlyCashFlowProfileRequestBody) GetInstitutionOk() (*MonthlyCashFlowProfileRequest, bool) {
	if o == nil || IsNil(o.Institution) {
		return nil, false
	}
	return o.Institution, true
}

// HasInstitution returns a boolean if a field has been set.
func (o *MonthlyCashFlowProfileRequestBody) HasInstitution() bool {
	if o != nil && !IsNil(o.Institution) {
		return true
	}

	return false
}

// SetInstitution gets a reference to the given MonthlyCashFlowProfileRequest and assigns it to the Institution field.
func (o *MonthlyCashFlowProfileRequestBody) SetInstitution(v MonthlyCashFlowProfileRequest) {
	o.Institution = &v
}

func (o MonthlyCashFlowProfileRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonthlyCashFlowProfileRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Institution) {
		toSerialize["institution"] = o.Institution
	}
	return toSerialize, nil
}

type NullableMonthlyCashFlowProfileRequestBody struct {
	value *MonthlyCashFlowProfileRequestBody
	isSet bool
}

func (v NullableMonthlyCashFlowProfileRequestBody) Get() *MonthlyCashFlowProfileRequestBody {
	return v.value
}

func (v *NullableMonthlyCashFlowProfileRequestBody) Set(val *MonthlyCashFlowProfileRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMonthlyCashFlowProfileRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMonthlyCashFlowProfileRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonthlyCashFlowProfileRequestBody(val *MonthlyCashFlowProfileRequestBody) *NullableMonthlyCashFlowProfileRequestBody {
	return &NullableMonthlyCashFlowProfileRequestBody{value: val, isSet: true}
}

func (v NullableMonthlyCashFlowProfileRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonthlyCashFlowProfileRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


