/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the EnhanceTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhanceTransactionsRequest{}

// EnhanceTransactionsRequest struct for EnhanceTransactionsRequest
type EnhanceTransactionsRequest struct {
	Amount *float32 `json:"amount,omitempty"`
	Description string `json:"description"`
	ExtendedTransactionType *string `json:"extended_transaction_type,omitempty"`
	Id string `json:"id"`
	Memo *string `json:"memo,omitempty"`
	MerchantCategoryCode *int32 `json:"merchant_category_code,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewEnhanceTransactionsRequest instantiates a new EnhanceTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhanceTransactionsRequest(description string, id string) *EnhanceTransactionsRequest {
	this := EnhanceTransactionsRequest{}
	this.Description = description
	this.Id = id
	return &this
}

// NewEnhanceTransactionsRequestWithDefaults instantiates a new EnhanceTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhanceTransactionsRequestWithDefaults() *EnhanceTransactionsRequest {
	this := EnhanceTransactionsRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *EnhanceTransactionsRequest) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *EnhanceTransactionsRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *EnhanceTransactionsRequest) SetAmount(v float32) {
	o.Amount = &v
}

// GetDescription returns the Description field value
func (o *EnhanceTransactionsRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *EnhanceTransactionsRequest) SetDescription(v string) {
	o.Description = v
}

// GetExtendedTransactionType returns the ExtendedTransactionType field value if set, zero value otherwise.
func (o *EnhanceTransactionsRequest) GetExtendedTransactionType() string {
	if o == nil || IsNil(o.ExtendedTransactionType) {
		var ret string
		return ret
	}
	return *o.ExtendedTransactionType
}

// GetExtendedTransactionTypeOk returns a tuple with the ExtendedTransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetExtendedTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExtendedTransactionType) {
		return nil, false
	}
	return o.ExtendedTransactionType, true
}

// HasExtendedTransactionType returns a boolean if a field has been set.
func (o *EnhanceTransactionsRequest) HasExtendedTransactionType() bool {
	if o != nil && !IsNil(o.ExtendedTransactionType) {
		return true
	}

	return false
}

// SetExtendedTransactionType gets a reference to the given string and assigns it to the ExtendedTransactionType field.
func (o *EnhanceTransactionsRequest) SetExtendedTransactionType(v string) {
	o.ExtendedTransactionType = &v
}

// GetId returns the Id field value
func (o *EnhanceTransactionsRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EnhanceTransactionsRequest) SetId(v string) {
	o.Id = v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *EnhanceTransactionsRequest) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *EnhanceTransactionsRequest) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *EnhanceTransactionsRequest) SetMemo(v string) {
	o.Memo = &v
}

// GetMerchantCategoryCode returns the MerchantCategoryCode field value if set, zero value otherwise.
func (o *EnhanceTransactionsRequest) GetMerchantCategoryCode() int32 {
	if o == nil || IsNil(o.MerchantCategoryCode) {
		var ret int32
		return ret
	}
	return *o.MerchantCategoryCode
}

// GetMerchantCategoryCodeOk returns a tuple with the MerchantCategoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetMerchantCategoryCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.MerchantCategoryCode) {
		return nil, false
	}
	return o.MerchantCategoryCode, true
}

// HasMerchantCategoryCode returns a boolean if a field has been set.
func (o *EnhanceTransactionsRequest) HasMerchantCategoryCode() bool {
	if o != nil && !IsNil(o.MerchantCategoryCode) {
		return true
	}

	return false
}

// SetMerchantCategoryCode gets a reference to the given int32 and assigns it to the MerchantCategoryCode field.
func (o *EnhanceTransactionsRequest) SetMerchantCategoryCode(v int32) {
	o.MerchantCategoryCode = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EnhanceTransactionsRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhanceTransactionsRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EnhanceTransactionsRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EnhanceTransactionsRequest) SetType(v string) {
	o.Type = &v
}

func (o EnhanceTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhanceTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	toSerialize["description"] = o.Description
	if !IsNil(o.ExtendedTransactionType) {
		toSerialize["extended_transaction_type"] = o.ExtendedTransactionType
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	if !IsNil(o.MerchantCategoryCode) {
		toSerialize["merchant_category_code"] = o.MerchantCategoryCode
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableEnhanceTransactionsRequest struct {
	value *EnhanceTransactionsRequest
	isSet bool
}

func (v NullableEnhanceTransactionsRequest) Get() *EnhanceTransactionsRequest {
	return v.value
}

func (v *NullableEnhanceTransactionsRequest) Set(val *EnhanceTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhanceTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhanceTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhanceTransactionsRequest(val *EnhanceTransactionsRequest) *NullableEnhanceTransactionsRequest {
	return &NullableEnhanceTransactionsRequest{value: val, isSet: true}
}

func (v NullableEnhanceTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhanceTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


