/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the BudgetCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BudgetCreateRequest{}

// BudgetCreateRequest struct for BudgetCreateRequest
type BudgetCreateRequest struct {
	// Unique identifier of the category.
	CategoryGuid string `json:"category_guid"`
	// Unique identifier of the parent budget. This is only required when creating a budget on a sub-category.
	ParentGuid string `json:"parent_guid"`
	// Amount of the budget.
	Amount *int32 `json:"amount,omitempty"`
	// Additional information a partner can store on the budget.
	Metadata *string `json:"metadata,omitempty"`
	// When set to true, this parameter will prevent a webhook from being triggered by the request.
	SkipWebhook *bool `json:"skip_webhook,omitempty"`
}

// NewBudgetCreateRequest instantiates a new BudgetCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBudgetCreateRequest(categoryGuid string, parentGuid string) *BudgetCreateRequest {
	this := BudgetCreateRequest{}
	this.CategoryGuid = categoryGuid
	this.ParentGuid = parentGuid
	return &this
}

// NewBudgetCreateRequestWithDefaults instantiates a new BudgetCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBudgetCreateRequestWithDefaults() *BudgetCreateRequest {
	this := BudgetCreateRequest{}
	return &this
}

// GetCategoryGuid returns the CategoryGuid field value
func (o *BudgetCreateRequest) GetCategoryGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CategoryGuid
}

// GetCategoryGuidOk returns a tuple with the CategoryGuid field value
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequest) GetCategoryGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CategoryGuid, true
}

// SetCategoryGuid sets field value
func (o *BudgetCreateRequest) SetCategoryGuid(v string) {
	o.CategoryGuid = v
}

// GetParentGuid returns the ParentGuid field value
func (o *BudgetCreateRequest) GetParentGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentGuid
}

// GetParentGuidOk returns a tuple with the ParentGuid field value
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequest) GetParentGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentGuid, true
}

// SetParentGuid sets field value
func (o *BudgetCreateRequest) SetParentGuid(v string) {
	o.ParentGuid = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *BudgetCreateRequest) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequest) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *BudgetCreateRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *BudgetCreateRequest) SetAmount(v int32) {
	o.Amount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *BudgetCreateRequest) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequest) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BudgetCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *BudgetCreateRequest) SetMetadata(v string) {
	o.Metadata = &v
}

// GetSkipWebhook returns the SkipWebhook field value if set, zero value otherwise.
func (o *BudgetCreateRequest) GetSkipWebhook() bool {
	if o == nil || IsNil(o.SkipWebhook) {
		var ret bool
		return ret
	}
	return *o.SkipWebhook
}

// GetSkipWebhookOk returns a tuple with the SkipWebhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequest) GetSkipWebhookOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipWebhook) {
		return nil, false
	}
	return o.SkipWebhook, true
}

// HasSkipWebhook returns a boolean if a field has been set.
func (o *BudgetCreateRequest) HasSkipWebhook() bool {
	if o != nil && !IsNil(o.SkipWebhook) {
		return true
	}

	return false
}

// SetSkipWebhook gets a reference to the given bool and assigns it to the SkipWebhook field.
func (o *BudgetCreateRequest) SetSkipWebhook(v bool) {
	o.SkipWebhook = &v
}

func (o BudgetCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BudgetCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["category_guid"] = o.CategoryGuid
	toSerialize["parent_guid"] = o.ParentGuid
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.SkipWebhook) {
		toSerialize["skip_webhook"] = o.SkipWebhook
	}
	return toSerialize, nil
}

type NullableBudgetCreateRequest struct {
	value *BudgetCreateRequest
	isSet bool
}

func (v NullableBudgetCreateRequest) Get() *BudgetCreateRequest {
	return v.value
}

func (v *NullableBudgetCreateRequest) Set(val *BudgetCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBudgetCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBudgetCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBudgetCreateRequest(val *BudgetCreateRequest) *NullableBudgetCreateRequest {
	return &NullableBudgetCreateRequest{value: val, isSet: true}
}

func (v NullableBudgetCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBudgetCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


