/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the TransactionIncludesResponseAllOfRepeatingTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionIncludesResponseAllOfRepeatingTransaction{}

// TransactionIncludesResponseAllOfRepeatingTransaction struct for TransactionIncludesResponseAllOfRepeatingTransaction
type TransactionIncludesResponseAllOfRepeatingTransaction struct {
	RepeatingTransactionType *string `json:"repeating_transaction_type,omitempty"`
	RecurrenceType *string `json:"recurrence_type,omitempty"`
	Guid *string `json:"guid,omitempty"`
}

// NewTransactionIncludesResponseAllOfRepeatingTransaction instantiates a new TransactionIncludesResponseAllOfRepeatingTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionIncludesResponseAllOfRepeatingTransaction() *TransactionIncludesResponseAllOfRepeatingTransaction {
	this := TransactionIncludesResponseAllOfRepeatingTransaction{}
	return &this
}

// NewTransactionIncludesResponseAllOfRepeatingTransactionWithDefaults instantiates a new TransactionIncludesResponseAllOfRepeatingTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionIncludesResponseAllOfRepeatingTransactionWithDefaults() *TransactionIncludesResponseAllOfRepeatingTransaction {
	this := TransactionIncludesResponseAllOfRepeatingTransaction{}
	return &this
}

// GetRepeatingTransactionType returns the RepeatingTransactionType field value if set, zero value otherwise.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetRepeatingTransactionType() string {
	if o == nil || IsNil(o.RepeatingTransactionType) {
		var ret string
		return ret
	}
	return *o.RepeatingTransactionType
}

// GetRepeatingTransactionTypeOk returns a tuple with the RepeatingTransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetRepeatingTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RepeatingTransactionType) {
		return nil, false
	}
	return o.RepeatingTransactionType, true
}

// HasRepeatingTransactionType returns a boolean if a field has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) HasRepeatingTransactionType() bool {
	if o != nil && !IsNil(o.RepeatingTransactionType) {
		return true
	}

	return false
}

// SetRepeatingTransactionType gets a reference to the given string and assigns it to the RepeatingTransactionType field.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) SetRepeatingTransactionType(v string) {
	o.RepeatingTransactionType = &v
}

// GetRecurrenceType returns the RecurrenceType field value if set, zero value otherwise.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetRecurrenceType() string {
	if o == nil || IsNil(o.RecurrenceType) {
		var ret string
		return ret
	}
	return *o.RecurrenceType
}

// GetRecurrenceTypeOk returns a tuple with the RecurrenceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetRecurrenceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RecurrenceType) {
		return nil, false
	}
	return o.RecurrenceType, true
}

// HasRecurrenceType returns a boolean if a field has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) HasRecurrenceType() bool {
	if o != nil && !IsNil(o.RecurrenceType) {
		return true
	}

	return false
}

// SetRecurrenceType gets a reference to the given string and assigns it to the RecurrenceType field.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) SetRecurrenceType(v string) {
	o.RecurrenceType = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *TransactionIncludesResponseAllOfRepeatingTransaction) SetGuid(v string) {
	o.Guid = &v
}

func (o TransactionIncludesResponseAllOfRepeatingTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionIncludesResponseAllOfRepeatingTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RepeatingTransactionType) {
		toSerialize["repeating_transaction_type"] = o.RepeatingTransactionType
	}
	if !IsNil(o.RecurrenceType) {
		toSerialize["recurrence_type"] = o.RecurrenceType
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	return toSerialize, nil
}

type NullableTransactionIncludesResponseAllOfRepeatingTransaction struct {
	value *TransactionIncludesResponseAllOfRepeatingTransaction
	isSet bool
}

func (v NullableTransactionIncludesResponseAllOfRepeatingTransaction) Get() *TransactionIncludesResponseAllOfRepeatingTransaction {
	return v.value
}

func (v *NullableTransactionIncludesResponseAllOfRepeatingTransaction) Set(val *TransactionIncludesResponseAllOfRepeatingTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionIncludesResponseAllOfRepeatingTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionIncludesResponseAllOfRepeatingTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionIncludesResponseAllOfRepeatingTransaction(val *TransactionIncludesResponseAllOfRepeatingTransaction) *NullableTransactionIncludesResponseAllOfRepeatingTransaction {
	return &NullableTransactionIncludesResponseAllOfRepeatingTransaction{value: val, isSet: true}
}

func (v NullableTransactionIncludesResponseAllOfRepeatingTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionIncludesResponseAllOfRepeatingTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


