/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// InstitutionResponse struct for InstitutionResponse
type InstitutionResponse struct {
	Code NullableString `json:"code,omitempty"`
	InstructionalText NullableString `json:"instructional_text,omitempty"`
	MediumLogoUrl NullableString `json:"medium_logo_url,omitempty"`
	Name NullableString `json:"name,omitempty"`
	SmallLogoUrl NullableString `json:"small_logo_url,omitempty"`
	SupportsAccountIdentification NullableBool `json:"supports_account_identification,omitempty"`
	SupportsAccountStatement NullableBool `json:"supports_account_statement,omitempty"`
	SupportsAccountVerification NullableBool `json:"supports_account_verification,omitempty"`
	SupportsOauth NullableBool `json:"supports_oauth,omitempty"`
	SupportsTransactionHistory NullableBool `json:"supports_transaction_history,omitempty"`
	Url NullableString `json:"url,omitempty"`
}

// NewInstitutionResponse instantiates a new InstitutionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstitutionResponse() *InstitutionResponse {
	this := InstitutionResponse{}
	return &this
}

// NewInstitutionResponseWithDefaults instantiates a new InstitutionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstitutionResponseWithDefaults() *InstitutionResponse {
	this := InstitutionResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetCode() string {
	if o == nil || o.Code.Get() == nil {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *InstitutionResponse) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *InstitutionResponse) SetCode(v string) {
	o.Code.Set(&v)
}
// SetCodeNil sets the value for Code to be an explicit nil
func (o *InstitutionResponse) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *InstitutionResponse) UnsetCode() {
	o.Code.Unset()
}

// GetInstructionalText returns the InstructionalText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetInstructionalText() string {
	if o == nil || o.InstructionalText.Get() == nil {
		var ret string
		return ret
	}
	return *o.InstructionalText.Get()
}

// GetInstructionalTextOk returns a tuple with the InstructionalText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetInstructionalTextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InstructionalText.Get(), o.InstructionalText.IsSet()
}

// HasInstructionalText returns a boolean if a field has been set.
func (o *InstitutionResponse) HasInstructionalText() bool {
	if o != nil && o.InstructionalText.IsSet() {
		return true
	}

	return false
}

// SetInstructionalText gets a reference to the given NullableString and assigns it to the InstructionalText field.
func (o *InstitutionResponse) SetInstructionalText(v string) {
	o.InstructionalText.Set(&v)
}
// SetInstructionalTextNil sets the value for InstructionalText to be an explicit nil
func (o *InstitutionResponse) SetInstructionalTextNil() {
	o.InstructionalText.Set(nil)
}

// UnsetInstructionalText ensures that no value is present for InstructionalText, not even an explicit nil
func (o *InstitutionResponse) UnsetInstructionalText() {
	o.InstructionalText.Unset()
}

// GetMediumLogoUrl returns the MediumLogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetMediumLogoUrl() string {
	if o == nil || o.MediumLogoUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.MediumLogoUrl.Get()
}

// GetMediumLogoUrlOk returns a tuple with the MediumLogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetMediumLogoUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MediumLogoUrl.Get(), o.MediumLogoUrl.IsSet()
}

// HasMediumLogoUrl returns a boolean if a field has been set.
func (o *InstitutionResponse) HasMediumLogoUrl() bool {
	if o != nil && o.MediumLogoUrl.IsSet() {
		return true
	}

	return false
}

// SetMediumLogoUrl gets a reference to the given NullableString and assigns it to the MediumLogoUrl field.
func (o *InstitutionResponse) SetMediumLogoUrl(v string) {
	o.MediumLogoUrl.Set(&v)
}
// SetMediumLogoUrlNil sets the value for MediumLogoUrl to be an explicit nil
func (o *InstitutionResponse) SetMediumLogoUrlNil() {
	o.MediumLogoUrl.Set(nil)
}

// UnsetMediumLogoUrl ensures that no value is present for MediumLogoUrl, not even an explicit nil
func (o *InstitutionResponse) UnsetMediumLogoUrl() {
	o.MediumLogoUrl.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *InstitutionResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *InstitutionResponse) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *InstitutionResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *InstitutionResponse) UnsetName() {
	o.Name.Unset()
}

// GetSmallLogoUrl returns the SmallLogoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSmallLogoUrl() string {
	if o == nil || o.SmallLogoUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.SmallLogoUrl.Get()
}

// GetSmallLogoUrlOk returns a tuple with the SmallLogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSmallLogoUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SmallLogoUrl.Get(), o.SmallLogoUrl.IsSet()
}

// HasSmallLogoUrl returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSmallLogoUrl() bool {
	if o != nil && o.SmallLogoUrl.IsSet() {
		return true
	}

	return false
}

// SetSmallLogoUrl gets a reference to the given NullableString and assigns it to the SmallLogoUrl field.
func (o *InstitutionResponse) SetSmallLogoUrl(v string) {
	o.SmallLogoUrl.Set(&v)
}
// SetSmallLogoUrlNil sets the value for SmallLogoUrl to be an explicit nil
func (o *InstitutionResponse) SetSmallLogoUrlNil() {
	o.SmallLogoUrl.Set(nil)
}

// UnsetSmallLogoUrl ensures that no value is present for SmallLogoUrl, not even an explicit nil
func (o *InstitutionResponse) UnsetSmallLogoUrl() {
	o.SmallLogoUrl.Unset()
}

// GetSupportsAccountIdentification returns the SupportsAccountIdentification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSupportsAccountIdentification() bool {
	if o == nil || o.SupportsAccountIdentification.Get() == nil {
		var ret bool
		return ret
	}
	return *o.SupportsAccountIdentification.Get()
}

// GetSupportsAccountIdentificationOk returns a tuple with the SupportsAccountIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSupportsAccountIdentificationOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SupportsAccountIdentification.Get(), o.SupportsAccountIdentification.IsSet()
}

// HasSupportsAccountIdentification returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSupportsAccountIdentification() bool {
	if o != nil && o.SupportsAccountIdentification.IsSet() {
		return true
	}

	return false
}

// SetSupportsAccountIdentification gets a reference to the given NullableBool and assigns it to the SupportsAccountIdentification field.
func (o *InstitutionResponse) SetSupportsAccountIdentification(v bool) {
	o.SupportsAccountIdentification.Set(&v)
}
// SetSupportsAccountIdentificationNil sets the value for SupportsAccountIdentification to be an explicit nil
func (o *InstitutionResponse) SetSupportsAccountIdentificationNil() {
	o.SupportsAccountIdentification.Set(nil)
}

// UnsetSupportsAccountIdentification ensures that no value is present for SupportsAccountIdentification, not even an explicit nil
func (o *InstitutionResponse) UnsetSupportsAccountIdentification() {
	o.SupportsAccountIdentification.Unset()
}

// GetSupportsAccountStatement returns the SupportsAccountStatement field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSupportsAccountStatement() bool {
	if o == nil || o.SupportsAccountStatement.Get() == nil {
		var ret bool
		return ret
	}
	return *o.SupportsAccountStatement.Get()
}

// GetSupportsAccountStatementOk returns a tuple with the SupportsAccountStatement field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSupportsAccountStatementOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SupportsAccountStatement.Get(), o.SupportsAccountStatement.IsSet()
}

// HasSupportsAccountStatement returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSupportsAccountStatement() bool {
	if o != nil && o.SupportsAccountStatement.IsSet() {
		return true
	}

	return false
}

// SetSupportsAccountStatement gets a reference to the given NullableBool and assigns it to the SupportsAccountStatement field.
func (o *InstitutionResponse) SetSupportsAccountStatement(v bool) {
	o.SupportsAccountStatement.Set(&v)
}
// SetSupportsAccountStatementNil sets the value for SupportsAccountStatement to be an explicit nil
func (o *InstitutionResponse) SetSupportsAccountStatementNil() {
	o.SupportsAccountStatement.Set(nil)
}

// UnsetSupportsAccountStatement ensures that no value is present for SupportsAccountStatement, not even an explicit nil
func (o *InstitutionResponse) UnsetSupportsAccountStatement() {
	o.SupportsAccountStatement.Unset()
}

// GetSupportsAccountVerification returns the SupportsAccountVerification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSupportsAccountVerification() bool {
	if o == nil || o.SupportsAccountVerification.Get() == nil {
		var ret bool
		return ret
	}
	return *o.SupportsAccountVerification.Get()
}

// GetSupportsAccountVerificationOk returns a tuple with the SupportsAccountVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSupportsAccountVerificationOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SupportsAccountVerification.Get(), o.SupportsAccountVerification.IsSet()
}

// HasSupportsAccountVerification returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSupportsAccountVerification() bool {
	if o != nil && o.SupportsAccountVerification.IsSet() {
		return true
	}

	return false
}

// SetSupportsAccountVerification gets a reference to the given NullableBool and assigns it to the SupportsAccountVerification field.
func (o *InstitutionResponse) SetSupportsAccountVerification(v bool) {
	o.SupportsAccountVerification.Set(&v)
}
// SetSupportsAccountVerificationNil sets the value for SupportsAccountVerification to be an explicit nil
func (o *InstitutionResponse) SetSupportsAccountVerificationNil() {
	o.SupportsAccountVerification.Set(nil)
}

// UnsetSupportsAccountVerification ensures that no value is present for SupportsAccountVerification, not even an explicit nil
func (o *InstitutionResponse) UnsetSupportsAccountVerification() {
	o.SupportsAccountVerification.Unset()
}

// GetSupportsOauth returns the SupportsOauth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSupportsOauth() bool {
	if o == nil || o.SupportsOauth.Get() == nil {
		var ret bool
		return ret
	}
	return *o.SupportsOauth.Get()
}

// GetSupportsOauthOk returns a tuple with the SupportsOauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSupportsOauthOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SupportsOauth.Get(), o.SupportsOauth.IsSet()
}

// HasSupportsOauth returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSupportsOauth() bool {
	if o != nil && o.SupportsOauth.IsSet() {
		return true
	}

	return false
}

// SetSupportsOauth gets a reference to the given NullableBool and assigns it to the SupportsOauth field.
func (o *InstitutionResponse) SetSupportsOauth(v bool) {
	o.SupportsOauth.Set(&v)
}
// SetSupportsOauthNil sets the value for SupportsOauth to be an explicit nil
func (o *InstitutionResponse) SetSupportsOauthNil() {
	o.SupportsOauth.Set(nil)
}

// UnsetSupportsOauth ensures that no value is present for SupportsOauth, not even an explicit nil
func (o *InstitutionResponse) UnsetSupportsOauth() {
	o.SupportsOauth.Unset()
}

// GetSupportsTransactionHistory returns the SupportsTransactionHistory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetSupportsTransactionHistory() bool {
	if o == nil || o.SupportsTransactionHistory.Get() == nil {
		var ret bool
		return ret
	}
	return *o.SupportsTransactionHistory.Get()
}

// GetSupportsTransactionHistoryOk returns a tuple with the SupportsTransactionHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetSupportsTransactionHistoryOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SupportsTransactionHistory.Get(), o.SupportsTransactionHistory.IsSet()
}

// HasSupportsTransactionHistory returns a boolean if a field has been set.
func (o *InstitutionResponse) HasSupportsTransactionHistory() bool {
	if o != nil && o.SupportsTransactionHistory.IsSet() {
		return true
	}

	return false
}

// SetSupportsTransactionHistory gets a reference to the given NullableBool and assigns it to the SupportsTransactionHistory field.
func (o *InstitutionResponse) SetSupportsTransactionHistory(v bool) {
	o.SupportsTransactionHistory.Set(&v)
}
// SetSupportsTransactionHistoryNil sets the value for SupportsTransactionHistory to be an explicit nil
func (o *InstitutionResponse) SetSupportsTransactionHistoryNil() {
	o.SupportsTransactionHistory.Set(nil)
}

// UnsetSupportsTransactionHistory ensures that no value is present for SupportsTransactionHistory, not even an explicit nil
func (o *InstitutionResponse) UnsetSupportsTransactionHistory() {
	o.SupportsTransactionHistory.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstitutionResponse) GetUrl() string {
	if o == nil || o.Url.Get() == nil {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstitutionResponse) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *InstitutionResponse) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *InstitutionResponse) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *InstitutionResponse) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *InstitutionResponse) UnsetUrl() {
	o.Url.Unset()
}

func (o InstitutionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.InstructionalText.IsSet() {
		toSerialize["instructional_text"] = o.InstructionalText.Get()
	}
	if o.MediumLogoUrl.IsSet() {
		toSerialize["medium_logo_url"] = o.MediumLogoUrl.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.SmallLogoUrl.IsSet() {
		toSerialize["small_logo_url"] = o.SmallLogoUrl.Get()
	}
	if o.SupportsAccountIdentification.IsSet() {
		toSerialize["supports_account_identification"] = o.SupportsAccountIdentification.Get()
	}
	if o.SupportsAccountStatement.IsSet() {
		toSerialize["supports_account_statement"] = o.SupportsAccountStatement.Get()
	}
	if o.SupportsAccountVerification.IsSet() {
		toSerialize["supports_account_verification"] = o.SupportsAccountVerification.Get()
	}
	if o.SupportsOauth.IsSet() {
		toSerialize["supports_oauth"] = o.SupportsOauth.Get()
	}
	if o.SupportsTransactionHistory.IsSet() {
		toSerialize["supports_transaction_history"] = o.SupportsTransactionHistory.Get()
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableInstitutionResponse struct {
	value *InstitutionResponse
	isSet bool
}

func (v NullableInstitutionResponse) Get() *InstitutionResponse {
	return v.value
}

func (v *NullableInstitutionResponse) Set(val *InstitutionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInstitutionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInstitutionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstitutionResponse(val *InstitutionResponse) *NullableInstitutionResponse {
	return &NullableInstitutionResponse{value: val, isSet: true}
}

func (v NullableInstitutionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstitutionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


