/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// SpendingPlanIterationItemCreateRequestBody struct for SpendingPlanIterationItemCreateRequestBody
type SpendingPlanIterationItemCreateRequestBody struct {
	CategoryGuid *string `json:"category_guid,omitempty"`
	ItemType *float32 `json:"item_type,omitempty"`
	PlannedAmount float32 `json:"planned_amount"`
	ScheduledPaymentGuid *string `json:"scheduled_payment_guid,omitempty"`
	TopLevelCategoryGuid *string `json:"top_level_category_guid,omitempty"`
}

// NewSpendingPlanIterationItemCreateRequestBody instantiates a new SpendingPlanIterationItemCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpendingPlanIterationItemCreateRequestBody(plannedAmount float32) *SpendingPlanIterationItemCreateRequestBody {
	this := SpendingPlanIterationItemCreateRequestBody{}
	this.PlannedAmount = plannedAmount
	return &this
}

// NewSpendingPlanIterationItemCreateRequestBodyWithDefaults instantiates a new SpendingPlanIterationItemCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpendingPlanIterationItemCreateRequestBodyWithDefaults() *SpendingPlanIterationItemCreateRequestBody {
	this := SpendingPlanIterationItemCreateRequestBody{}
	return &this
}

// GetCategoryGuid returns the CategoryGuid field value if set, zero value otherwise.
func (o *SpendingPlanIterationItemCreateRequestBody) GetCategoryGuid() string {
	if o == nil || o.CategoryGuid == nil {
		var ret string
		return ret
	}
	return *o.CategoryGuid
}

// GetCategoryGuidOk returns a tuple with the CategoryGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) GetCategoryGuidOk() (*string, bool) {
	if o == nil || o.CategoryGuid == nil {
		return nil, false
	}
	return o.CategoryGuid, true
}

// HasCategoryGuid returns a boolean if a field has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) HasCategoryGuid() bool {
	if o != nil && o.CategoryGuid != nil {
		return true
	}

	return false
}

// SetCategoryGuid gets a reference to the given string and assigns it to the CategoryGuid field.
func (o *SpendingPlanIterationItemCreateRequestBody) SetCategoryGuid(v string) {
	o.CategoryGuid = &v
}

// GetItemType returns the ItemType field value if set, zero value otherwise.
func (o *SpendingPlanIterationItemCreateRequestBody) GetItemType() float32 {
	if o == nil || o.ItemType == nil {
		var ret float32
		return ret
	}
	return *o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) GetItemTypeOk() (*float32, bool) {
	if o == nil || o.ItemType == nil {
		return nil, false
	}
	return o.ItemType, true
}

// HasItemType returns a boolean if a field has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) HasItemType() bool {
	if o != nil && o.ItemType != nil {
		return true
	}

	return false
}

// SetItemType gets a reference to the given float32 and assigns it to the ItemType field.
func (o *SpendingPlanIterationItemCreateRequestBody) SetItemType(v float32) {
	o.ItemType = &v
}

// GetPlannedAmount returns the PlannedAmount field value
func (o *SpendingPlanIterationItemCreateRequestBody) GetPlannedAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PlannedAmount
}

// GetPlannedAmountOk returns a tuple with the PlannedAmount field value
// and a boolean to check if the value has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) GetPlannedAmountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlannedAmount, true
}

// SetPlannedAmount sets field value
func (o *SpendingPlanIterationItemCreateRequestBody) SetPlannedAmount(v float32) {
	o.PlannedAmount = v
}

// GetScheduledPaymentGuid returns the ScheduledPaymentGuid field value if set, zero value otherwise.
func (o *SpendingPlanIterationItemCreateRequestBody) GetScheduledPaymentGuid() string {
	if o == nil || o.ScheduledPaymentGuid == nil {
		var ret string
		return ret
	}
	return *o.ScheduledPaymentGuid
}

// GetScheduledPaymentGuidOk returns a tuple with the ScheduledPaymentGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) GetScheduledPaymentGuidOk() (*string, bool) {
	if o == nil || o.ScheduledPaymentGuid == nil {
		return nil, false
	}
	return o.ScheduledPaymentGuid, true
}

// HasScheduledPaymentGuid returns a boolean if a field has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) HasScheduledPaymentGuid() bool {
	if o != nil && o.ScheduledPaymentGuid != nil {
		return true
	}

	return false
}

// SetScheduledPaymentGuid gets a reference to the given string and assigns it to the ScheduledPaymentGuid field.
func (o *SpendingPlanIterationItemCreateRequestBody) SetScheduledPaymentGuid(v string) {
	o.ScheduledPaymentGuid = &v
}

// GetTopLevelCategoryGuid returns the TopLevelCategoryGuid field value if set, zero value otherwise.
func (o *SpendingPlanIterationItemCreateRequestBody) GetTopLevelCategoryGuid() string {
	if o == nil || o.TopLevelCategoryGuid == nil {
		var ret string
		return ret
	}
	return *o.TopLevelCategoryGuid
}

// GetTopLevelCategoryGuidOk returns a tuple with the TopLevelCategoryGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) GetTopLevelCategoryGuidOk() (*string, bool) {
	if o == nil || o.TopLevelCategoryGuid == nil {
		return nil, false
	}
	return o.TopLevelCategoryGuid, true
}

// HasTopLevelCategoryGuid returns a boolean if a field has been set.
func (o *SpendingPlanIterationItemCreateRequestBody) HasTopLevelCategoryGuid() bool {
	if o != nil && o.TopLevelCategoryGuid != nil {
		return true
	}

	return false
}

// SetTopLevelCategoryGuid gets a reference to the given string and assigns it to the TopLevelCategoryGuid field.
func (o *SpendingPlanIterationItemCreateRequestBody) SetTopLevelCategoryGuid(v string) {
	o.TopLevelCategoryGuid = &v
}

func (o SpendingPlanIterationItemCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CategoryGuid != nil {
		toSerialize["category_guid"] = o.CategoryGuid
	}
	if o.ItemType != nil {
		toSerialize["item_type"] = o.ItemType
	}
	if true {
		toSerialize["planned_amount"] = o.PlannedAmount
	}
	if o.ScheduledPaymentGuid != nil {
		toSerialize["scheduled_payment_guid"] = o.ScheduledPaymentGuid
	}
	if o.TopLevelCategoryGuid != nil {
		toSerialize["top_level_category_guid"] = o.TopLevelCategoryGuid
	}
	return json.Marshal(toSerialize)
}

type NullableSpendingPlanIterationItemCreateRequestBody struct {
	value *SpendingPlanIterationItemCreateRequestBody
	isSet bool
}

func (v NullableSpendingPlanIterationItemCreateRequestBody) Get() *SpendingPlanIterationItemCreateRequestBody {
	return v.value
}

func (v *NullableSpendingPlanIterationItemCreateRequestBody) Set(val *SpendingPlanIterationItemCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSpendingPlanIterationItemCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSpendingPlanIterationItemCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpendingPlanIterationItemCreateRequestBody(val *SpendingPlanIterationItemCreateRequestBody) *NullableSpendingPlanIterationItemCreateRequestBody {
	return &NullableSpendingPlanIterationItemCreateRequestBody{value: val, isSet: true}
}

func (v NullableSpendingPlanIterationItemCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpendingPlanIterationItemCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


