/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// StatementsResponseBody struct for StatementsResponseBody
type StatementsResponseBody struct {
	Pagination *PaginationResponse `json:"pagination,omitempty"`
	Statements *[]StatementResponse `json:"statements,omitempty"`
}

// NewStatementsResponseBody instantiates a new StatementsResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementsResponseBody() *StatementsResponseBody {
	this := StatementsResponseBody{}
	return &this
}

// NewStatementsResponseBodyWithDefaults instantiates a new StatementsResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementsResponseBodyWithDefaults() *StatementsResponseBody {
	this := StatementsResponseBody{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *StatementsResponseBody) GetPagination() PaginationResponse {
	if o == nil || o.Pagination == nil {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsResponseBody) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *StatementsResponseBody) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *StatementsResponseBody) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

// GetStatements returns the Statements field value if set, zero value otherwise.
func (o *StatementsResponseBody) GetStatements() []StatementResponse {
	if o == nil || o.Statements == nil {
		var ret []StatementResponse
		return ret
	}
	return *o.Statements
}

// GetStatementsOk returns a tuple with the Statements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsResponseBody) GetStatementsOk() (*[]StatementResponse, bool) {
	if o == nil || o.Statements == nil {
		return nil, false
	}
	return o.Statements, true
}

// HasStatements returns a boolean if a field has been set.
func (o *StatementsResponseBody) HasStatements() bool {
	if o != nil && o.Statements != nil {
		return true
	}

	return false
}

// SetStatements gets a reference to the given []StatementResponse and assigns it to the Statements field.
func (o *StatementsResponseBody) SetStatements(v []StatementResponse) {
	o.Statements = &v
}

func (o StatementsResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	if o.Statements != nil {
		toSerialize["statements"] = o.Statements
	}
	return json.Marshal(toSerialize)
}

type NullableStatementsResponseBody struct {
	value *StatementsResponseBody
	isSet bool
}

func (v NullableStatementsResponseBody) Get() *StatementsResponseBody {
	return v.value
}

func (v *NullableStatementsResponseBody) Set(val *StatementsResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementsResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementsResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementsResponseBody(val *StatementsResponseBody) *NullableStatementsResponseBody {
	return &NullableStatementsResponseBody{value: val, isSet: true}
}

func (v NullableStatementsResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementsResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


