/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// AccountsResponseBody struct for AccountsResponseBody
type AccountsResponseBody struct {
	Accounts *[]AccountResponse `json:"accounts,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewAccountsResponseBody instantiates a new AccountsResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountsResponseBody() *AccountsResponseBody {
	this := AccountsResponseBody{}
	return &this
}

// NewAccountsResponseBodyWithDefaults instantiates a new AccountsResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountsResponseBodyWithDefaults() *AccountsResponseBody {
	this := AccountsResponseBody{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *AccountsResponseBody) GetAccounts() []AccountResponse {
	if o == nil || o.Accounts == nil {
		var ret []AccountResponse
		return ret
	}
	return *o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountsResponseBody) GetAccountsOk() (*[]AccountResponse, bool) {
	if o == nil || o.Accounts == nil {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *AccountsResponseBody) HasAccounts() bool {
	if o != nil && o.Accounts != nil {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []AccountResponse and assigns it to the Accounts field.
func (o *AccountsResponseBody) SetAccounts(v []AccountResponse) {
	o.Accounts = &v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *AccountsResponseBody) GetPagination() PaginationResponse {
	if o == nil || o.Pagination == nil {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountsResponseBody) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *AccountsResponseBody) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *AccountsResponseBody) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o AccountsResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Accounts != nil {
		toSerialize["accounts"] = o.Accounts
	}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	return json.Marshal(toSerialize)
}

type NullableAccountsResponseBody struct {
	value *AccountsResponseBody
	isSet bool
}

func (v NullableAccountsResponseBody) Get() *AccountsResponseBody {
	return v.value
}

func (v *NullableAccountsResponseBody) Set(val *AccountsResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountsResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountsResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountsResponseBody(val *AccountsResponseBody) *NullableAccountsResponseBody {
	return &NullableAccountsResponseBody{value: val, isSet: true}
}

func (v NullableAccountsResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountsResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


