/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the BudgetCreateRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BudgetCreateRequestBody{}

// BudgetCreateRequestBody struct for BudgetCreateRequestBody
type BudgetCreateRequestBody struct {
	Budget *BudgetCreateRequest `json:"budget,omitempty"`
}

// NewBudgetCreateRequestBody instantiates a new BudgetCreateRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBudgetCreateRequestBody() *BudgetCreateRequestBody {
	this := BudgetCreateRequestBody{}
	return &this
}

// NewBudgetCreateRequestBodyWithDefaults instantiates a new BudgetCreateRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBudgetCreateRequestBodyWithDefaults() *BudgetCreateRequestBody {
	this := BudgetCreateRequestBody{}
	return &this
}

// GetBudget returns the Budget field value if set, zero value otherwise.
func (o *BudgetCreateRequestBody) GetBudget() BudgetCreateRequest {
	if o == nil || IsNil(o.Budget) {
		var ret BudgetCreateRequest
		return ret
	}
	return *o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BudgetCreateRequestBody) GetBudgetOk() (*BudgetCreateRequest, bool) {
	if o == nil || IsNil(o.Budget) {
		return nil, false
	}
	return o.Budget, true
}

// HasBudget returns a boolean if a field has been set.
func (o *BudgetCreateRequestBody) HasBudget() bool {
	if o != nil && !IsNil(o.Budget) {
		return true
	}

	return false
}

// SetBudget gets a reference to the given BudgetCreateRequest and assigns it to the Budget field.
func (o *BudgetCreateRequestBody) SetBudget(v BudgetCreateRequest) {
	o.Budget = &v
}

func (o BudgetCreateRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BudgetCreateRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Budget) {
		toSerialize["budget"] = o.Budget
	}
	return toSerialize, nil
}

type NullableBudgetCreateRequestBody struct {
	value *BudgetCreateRequestBody
	isSet bool
}

func (v NullableBudgetCreateRequestBody) Get() *BudgetCreateRequestBody {
	return v.value
}

func (v *NullableBudgetCreateRequestBody) Set(val *BudgetCreateRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBudgetCreateRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBudgetCreateRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBudgetCreateRequestBody(val *BudgetCreateRequestBody) *NullableBudgetCreateRequestBody {
	return &NullableBudgetCreateRequestBody{value: val, isSet: true}
}

func (v NullableBudgetCreateRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBudgetCreateRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


