/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the ACHResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ACHResponse{}

// ACHResponse struct for ACHResponse
type ACHResponse struct {
	AccountGuid *string `json:"account_guid,omitempty"`
	AccountNumberLastFour NullableString `json:"account_number_last_four,omitempty"`
	AccountType NullableString `json:"account_type,omitempty"`
	AchInitiatedAt NullableString `json:"ach_initiated_at,omitempty"`
	ClientGuid *string `json:"client_guid,omitempty"`
	CorrectedAccountNumber NullableString `json:"corrected_account_number,omitempty"`
	CorrectedRoutingNumber NullableString `json:"corrected_routing_number,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Guid *string `json:"guid,omitempty"`
	Id *string `json:"id,omitempty"`
	InstitutionGuid *string `json:"institution_guid,omitempty"`
	InvestigationNotes NullableString `json:"investigation_notes,omitempty"`
	MemberGuid *string `json:"member_guid,omitempty"`
	ProcessingErrors NullableString `json:"processing_errors,omitempty"`
	ResolutionCode NullableString `json:"resolution_code,omitempty"`
	ResolutionDetail NullableString `json:"resolution_detail,omitempty"`
	ResolvedStatusAt NullableString `json:"resolved_status_at,omitempty"`
	ReturnCode *string `json:"return_code,omitempty"`
	ReturnNotes NullableString `json:"return_notes,omitempty"`
	ReturnAccountNumber NullableString `json:"return_account_number,omitempty"`
	ReturnRoutingNumber NullableString `json:"return_routing_number,omitempty"`
	ReturnStatus NullableString `json:"return_status,omitempty"`
	ReturnedAt NullableString `json:"returned_at,omitempty"`
	SecCode NullableString `json:"sec_code,omitempty"`
	StartedProcessingAt NullableString `json:"started_processing_at,omitempty"`
	SubmittedAt NullableString `json:"submitted_at,omitempty"`
	TransactionAmount NullableFloat64 `json:"transaction_amount,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UserGuid *string `json:"user_guid,omitempty"`
}

// NewACHResponse instantiates a new ACHResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewACHResponse() *ACHResponse {
	this := ACHResponse{}
	return &this
}

// NewACHResponseWithDefaults instantiates a new ACHResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewACHResponseWithDefaults() *ACHResponse {
	this := ACHResponse{}
	return &this
}

// GetAccountGuid returns the AccountGuid field value if set, zero value otherwise.
func (o *ACHResponse) GetAccountGuid() string {
	if o == nil || IsNil(o.AccountGuid) {
		var ret string
		return ret
	}
	return *o.AccountGuid
}

// GetAccountGuidOk returns a tuple with the AccountGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetAccountGuidOk() (*string, bool) {
	if o == nil || IsNil(o.AccountGuid) {
		return nil, false
	}
	return o.AccountGuid, true
}

// HasAccountGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasAccountGuid() bool {
	if o != nil && !IsNil(o.AccountGuid) {
		return true
	}

	return false
}

// SetAccountGuid gets a reference to the given string and assigns it to the AccountGuid field.
func (o *ACHResponse) SetAccountGuid(v string) {
	o.AccountGuid = &v
}

// GetAccountNumberLastFour returns the AccountNumberLastFour field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetAccountNumberLastFour() string {
	if o == nil || IsNil(o.AccountNumberLastFour.Get()) {
		var ret string
		return ret
	}
	return *o.AccountNumberLastFour.Get()
}

// GetAccountNumberLastFourOk returns a tuple with the AccountNumberLastFour field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetAccountNumberLastFourOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountNumberLastFour.Get(), o.AccountNumberLastFour.IsSet()
}

// HasAccountNumberLastFour returns a boolean if a field has been set.
func (o *ACHResponse) HasAccountNumberLastFour() bool {
	if o != nil && o.AccountNumberLastFour.IsSet() {
		return true
	}

	return false
}

// SetAccountNumberLastFour gets a reference to the given NullableString and assigns it to the AccountNumberLastFour field.
func (o *ACHResponse) SetAccountNumberLastFour(v string) {
	o.AccountNumberLastFour.Set(&v)
}
// SetAccountNumberLastFourNil sets the value for AccountNumberLastFour to be an explicit nil
func (o *ACHResponse) SetAccountNumberLastFourNil() {
	o.AccountNumberLastFour.Set(nil)
}

// UnsetAccountNumberLastFour ensures that no value is present for AccountNumberLastFour, not even an explicit nil
func (o *ACHResponse) UnsetAccountNumberLastFour() {
	o.AccountNumberLastFour.Unset()
}

// GetAccountType returns the AccountType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetAccountType() string {
	if o == nil || IsNil(o.AccountType.Get()) {
		var ret string
		return ret
	}
	return *o.AccountType.Get()
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetAccountTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountType.Get(), o.AccountType.IsSet()
}

// HasAccountType returns a boolean if a field has been set.
func (o *ACHResponse) HasAccountType() bool {
	if o != nil && o.AccountType.IsSet() {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given NullableString and assigns it to the AccountType field.
func (o *ACHResponse) SetAccountType(v string) {
	o.AccountType.Set(&v)
}
// SetAccountTypeNil sets the value for AccountType to be an explicit nil
func (o *ACHResponse) SetAccountTypeNil() {
	o.AccountType.Set(nil)
}

// UnsetAccountType ensures that no value is present for AccountType, not even an explicit nil
func (o *ACHResponse) UnsetAccountType() {
	o.AccountType.Unset()
}

// GetAchInitiatedAt returns the AchInitiatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetAchInitiatedAt() string {
	if o == nil || IsNil(o.AchInitiatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.AchInitiatedAt.Get()
}

// GetAchInitiatedAtOk returns a tuple with the AchInitiatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetAchInitiatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AchInitiatedAt.Get(), o.AchInitiatedAt.IsSet()
}

// HasAchInitiatedAt returns a boolean if a field has been set.
func (o *ACHResponse) HasAchInitiatedAt() bool {
	if o != nil && o.AchInitiatedAt.IsSet() {
		return true
	}

	return false
}

// SetAchInitiatedAt gets a reference to the given NullableString and assigns it to the AchInitiatedAt field.
func (o *ACHResponse) SetAchInitiatedAt(v string) {
	o.AchInitiatedAt.Set(&v)
}
// SetAchInitiatedAtNil sets the value for AchInitiatedAt to be an explicit nil
func (o *ACHResponse) SetAchInitiatedAtNil() {
	o.AchInitiatedAt.Set(nil)
}

// UnsetAchInitiatedAt ensures that no value is present for AchInitiatedAt, not even an explicit nil
func (o *ACHResponse) UnsetAchInitiatedAt() {
	o.AchInitiatedAt.Unset()
}

// GetClientGuid returns the ClientGuid field value if set, zero value otherwise.
func (o *ACHResponse) GetClientGuid() string {
	if o == nil || IsNil(o.ClientGuid) {
		var ret string
		return ret
	}
	return *o.ClientGuid
}

// GetClientGuidOk returns a tuple with the ClientGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetClientGuidOk() (*string, bool) {
	if o == nil || IsNil(o.ClientGuid) {
		return nil, false
	}
	return o.ClientGuid, true
}

// HasClientGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasClientGuid() bool {
	if o != nil && !IsNil(o.ClientGuid) {
		return true
	}

	return false
}

// SetClientGuid gets a reference to the given string and assigns it to the ClientGuid field.
func (o *ACHResponse) SetClientGuid(v string) {
	o.ClientGuid = &v
}

// GetCorrectedAccountNumber returns the CorrectedAccountNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetCorrectedAccountNumber() string {
	if o == nil || IsNil(o.CorrectedAccountNumber.Get()) {
		var ret string
		return ret
	}
	return *o.CorrectedAccountNumber.Get()
}

// GetCorrectedAccountNumberOk returns a tuple with the CorrectedAccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetCorrectedAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CorrectedAccountNumber.Get(), o.CorrectedAccountNumber.IsSet()
}

// HasCorrectedAccountNumber returns a boolean if a field has been set.
func (o *ACHResponse) HasCorrectedAccountNumber() bool {
	if o != nil && o.CorrectedAccountNumber.IsSet() {
		return true
	}

	return false
}

// SetCorrectedAccountNumber gets a reference to the given NullableString and assigns it to the CorrectedAccountNumber field.
func (o *ACHResponse) SetCorrectedAccountNumber(v string) {
	o.CorrectedAccountNumber.Set(&v)
}
// SetCorrectedAccountNumberNil sets the value for CorrectedAccountNumber to be an explicit nil
func (o *ACHResponse) SetCorrectedAccountNumberNil() {
	o.CorrectedAccountNumber.Set(nil)
}

// UnsetCorrectedAccountNumber ensures that no value is present for CorrectedAccountNumber, not even an explicit nil
func (o *ACHResponse) UnsetCorrectedAccountNumber() {
	o.CorrectedAccountNumber.Unset()
}

// GetCorrectedRoutingNumber returns the CorrectedRoutingNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetCorrectedRoutingNumber() string {
	if o == nil || IsNil(o.CorrectedRoutingNumber.Get()) {
		var ret string
		return ret
	}
	return *o.CorrectedRoutingNumber.Get()
}

// GetCorrectedRoutingNumberOk returns a tuple with the CorrectedRoutingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetCorrectedRoutingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CorrectedRoutingNumber.Get(), o.CorrectedRoutingNumber.IsSet()
}

// HasCorrectedRoutingNumber returns a boolean if a field has been set.
func (o *ACHResponse) HasCorrectedRoutingNumber() bool {
	if o != nil && o.CorrectedRoutingNumber.IsSet() {
		return true
	}

	return false
}

// SetCorrectedRoutingNumber gets a reference to the given NullableString and assigns it to the CorrectedRoutingNumber field.
func (o *ACHResponse) SetCorrectedRoutingNumber(v string) {
	o.CorrectedRoutingNumber.Set(&v)
}
// SetCorrectedRoutingNumberNil sets the value for CorrectedRoutingNumber to be an explicit nil
func (o *ACHResponse) SetCorrectedRoutingNumberNil() {
	o.CorrectedRoutingNumber.Set(nil)
}

// UnsetCorrectedRoutingNumber ensures that no value is present for CorrectedRoutingNumber, not even an explicit nil
func (o *ACHResponse) UnsetCorrectedRoutingNumber() {
	o.CorrectedRoutingNumber.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ACHResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ACHResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ACHResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *ACHResponse) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *ACHResponse) SetGuid(v string) {
	o.Guid = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ACHResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ACHResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ACHResponse) SetId(v string) {
	o.Id = &v
}

// GetInstitutionGuid returns the InstitutionGuid field value if set, zero value otherwise.
func (o *ACHResponse) GetInstitutionGuid() string {
	if o == nil || IsNil(o.InstitutionGuid) {
		var ret string
		return ret
	}
	return *o.InstitutionGuid
}

// GetInstitutionGuidOk returns a tuple with the InstitutionGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetInstitutionGuidOk() (*string, bool) {
	if o == nil || IsNil(o.InstitutionGuid) {
		return nil, false
	}
	return o.InstitutionGuid, true
}

// HasInstitutionGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasInstitutionGuid() bool {
	if o != nil && !IsNil(o.InstitutionGuid) {
		return true
	}

	return false
}

// SetInstitutionGuid gets a reference to the given string and assigns it to the InstitutionGuid field.
func (o *ACHResponse) SetInstitutionGuid(v string) {
	o.InstitutionGuid = &v
}

// GetInvestigationNotes returns the InvestigationNotes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetInvestigationNotes() string {
	if o == nil || IsNil(o.InvestigationNotes.Get()) {
		var ret string
		return ret
	}
	return *o.InvestigationNotes.Get()
}

// GetInvestigationNotesOk returns a tuple with the InvestigationNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetInvestigationNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvestigationNotes.Get(), o.InvestigationNotes.IsSet()
}

// HasInvestigationNotes returns a boolean if a field has been set.
func (o *ACHResponse) HasInvestigationNotes() bool {
	if o != nil && o.InvestigationNotes.IsSet() {
		return true
	}

	return false
}

// SetInvestigationNotes gets a reference to the given NullableString and assigns it to the InvestigationNotes field.
func (o *ACHResponse) SetInvestigationNotes(v string) {
	o.InvestigationNotes.Set(&v)
}
// SetInvestigationNotesNil sets the value for InvestigationNotes to be an explicit nil
func (o *ACHResponse) SetInvestigationNotesNil() {
	o.InvestigationNotes.Set(nil)
}

// UnsetInvestigationNotes ensures that no value is present for InvestigationNotes, not even an explicit nil
func (o *ACHResponse) UnsetInvestigationNotes() {
	o.InvestigationNotes.Unset()
}

// GetMemberGuid returns the MemberGuid field value if set, zero value otherwise.
func (o *ACHResponse) GetMemberGuid() string {
	if o == nil || IsNil(o.MemberGuid) {
		var ret string
		return ret
	}
	return *o.MemberGuid
}

// GetMemberGuidOk returns a tuple with the MemberGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetMemberGuidOk() (*string, bool) {
	if o == nil || IsNil(o.MemberGuid) {
		return nil, false
	}
	return o.MemberGuid, true
}

// HasMemberGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasMemberGuid() bool {
	if o != nil && !IsNil(o.MemberGuid) {
		return true
	}

	return false
}

// SetMemberGuid gets a reference to the given string and assigns it to the MemberGuid field.
func (o *ACHResponse) SetMemberGuid(v string) {
	o.MemberGuid = &v
}

// GetProcessingErrors returns the ProcessingErrors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetProcessingErrors() string {
	if o == nil || IsNil(o.ProcessingErrors.Get()) {
		var ret string
		return ret
	}
	return *o.ProcessingErrors.Get()
}

// GetProcessingErrorsOk returns a tuple with the ProcessingErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetProcessingErrorsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProcessingErrors.Get(), o.ProcessingErrors.IsSet()
}

// HasProcessingErrors returns a boolean if a field has been set.
func (o *ACHResponse) HasProcessingErrors() bool {
	if o != nil && o.ProcessingErrors.IsSet() {
		return true
	}

	return false
}

// SetProcessingErrors gets a reference to the given NullableString and assigns it to the ProcessingErrors field.
func (o *ACHResponse) SetProcessingErrors(v string) {
	o.ProcessingErrors.Set(&v)
}
// SetProcessingErrorsNil sets the value for ProcessingErrors to be an explicit nil
func (o *ACHResponse) SetProcessingErrorsNil() {
	o.ProcessingErrors.Set(nil)
}

// UnsetProcessingErrors ensures that no value is present for ProcessingErrors, not even an explicit nil
func (o *ACHResponse) UnsetProcessingErrors() {
	o.ProcessingErrors.Unset()
}

// GetResolutionCode returns the ResolutionCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetResolutionCode() string {
	if o == nil || IsNil(o.ResolutionCode.Get()) {
		var ret string
		return ret
	}
	return *o.ResolutionCode.Get()
}

// GetResolutionCodeOk returns a tuple with the ResolutionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetResolutionCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolutionCode.Get(), o.ResolutionCode.IsSet()
}

// HasResolutionCode returns a boolean if a field has been set.
func (o *ACHResponse) HasResolutionCode() bool {
	if o != nil && o.ResolutionCode.IsSet() {
		return true
	}

	return false
}

// SetResolutionCode gets a reference to the given NullableString and assigns it to the ResolutionCode field.
func (o *ACHResponse) SetResolutionCode(v string) {
	o.ResolutionCode.Set(&v)
}
// SetResolutionCodeNil sets the value for ResolutionCode to be an explicit nil
func (o *ACHResponse) SetResolutionCodeNil() {
	o.ResolutionCode.Set(nil)
}

// UnsetResolutionCode ensures that no value is present for ResolutionCode, not even an explicit nil
func (o *ACHResponse) UnsetResolutionCode() {
	o.ResolutionCode.Unset()
}

// GetResolutionDetail returns the ResolutionDetail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetResolutionDetail() string {
	if o == nil || IsNil(o.ResolutionDetail.Get()) {
		var ret string
		return ret
	}
	return *o.ResolutionDetail.Get()
}

// GetResolutionDetailOk returns a tuple with the ResolutionDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetResolutionDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolutionDetail.Get(), o.ResolutionDetail.IsSet()
}

// HasResolutionDetail returns a boolean if a field has been set.
func (o *ACHResponse) HasResolutionDetail() bool {
	if o != nil && o.ResolutionDetail.IsSet() {
		return true
	}

	return false
}

// SetResolutionDetail gets a reference to the given NullableString and assigns it to the ResolutionDetail field.
func (o *ACHResponse) SetResolutionDetail(v string) {
	o.ResolutionDetail.Set(&v)
}
// SetResolutionDetailNil sets the value for ResolutionDetail to be an explicit nil
func (o *ACHResponse) SetResolutionDetailNil() {
	o.ResolutionDetail.Set(nil)
}

// UnsetResolutionDetail ensures that no value is present for ResolutionDetail, not even an explicit nil
func (o *ACHResponse) UnsetResolutionDetail() {
	o.ResolutionDetail.Unset()
}

// GetResolvedStatusAt returns the ResolvedStatusAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetResolvedStatusAt() string {
	if o == nil || IsNil(o.ResolvedStatusAt.Get()) {
		var ret string
		return ret
	}
	return *o.ResolvedStatusAt.Get()
}

// GetResolvedStatusAtOk returns a tuple with the ResolvedStatusAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetResolvedStatusAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolvedStatusAt.Get(), o.ResolvedStatusAt.IsSet()
}

// HasResolvedStatusAt returns a boolean if a field has been set.
func (o *ACHResponse) HasResolvedStatusAt() bool {
	if o != nil && o.ResolvedStatusAt.IsSet() {
		return true
	}

	return false
}

// SetResolvedStatusAt gets a reference to the given NullableString and assigns it to the ResolvedStatusAt field.
func (o *ACHResponse) SetResolvedStatusAt(v string) {
	o.ResolvedStatusAt.Set(&v)
}
// SetResolvedStatusAtNil sets the value for ResolvedStatusAt to be an explicit nil
func (o *ACHResponse) SetResolvedStatusAtNil() {
	o.ResolvedStatusAt.Set(nil)
}

// UnsetResolvedStatusAt ensures that no value is present for ResolvedStatusAt, not even an explicit nil
func (o *ACHResponse) UnsetResolvedStatusAt() {
	o.ResolvedStatusAt.Unset()
}

// GetReturnCode returns the ReturnCode field value if set, zero value otherwise.
func (o *ACHResponse) GetReturnCode() string {
	if o == nil || IsNil(o.ReturnCode) {
		var ret string
		return ret
	}
	return *o.ReturnCode
}

// GetReturnCodeOk returns a tuple with the ReturnCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetReturnCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnCode) {
		return nil, false
	}
	return o.ReturnCode, true
}

// HasReturnCode returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnCode() bool {
	if o != nil && !IsNil(o.ReturnCode) {
		return true
	}

	return false
}

// SetReturnCode gets a reference to the given string and assigns it to the ReturnCode field.
func (o *ACHResponse) SetReturnCode(v string) {
	o.ReturnCode = &v
}

// GetReturnNotes returns the ReturnNotes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetReturnNotes() string {
	if o == nil || IsNil(o.ReturnNotes.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnNotes.Get()
}

// GetReturnNotesOk returns a tuple with the ReturnNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetReturnNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnNotes.Get(), o.ReturnNotes.IsSet()
}

// HasReturnNotes returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnNotes() bool {
	if o != nil && o.ReturnNotes.IsSet() {
		return true
	}

	return false
}

// SetReturnNotes gets a reference to the given NullableString and assigns it to the ReturnNotes field.
func (o *ACHResponse) SetReturnNotes(v string) {
	o.ReturnNotes.Set(&v)
}
// SetReturnNotesNil sets the value for ReturnNotes to be an explicit nil
func (o *ACHResponse) SetReturnNotesNil() {
	o.ReturnNotes.Set(nil)
}

// UnsetReturnNotes ensures that no value is present for ReturnNotes, not even an explicit nil
func (o *ACHResponse) UnsetReturnNotes() {
	o.ReturnNotes.Unset()
}

// GetReturnAccountNumber returns the ReturnAccountNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetReturnAccountNumber() string {
	if o == nil || IsNil(o.ReturnAccountNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnAccountNumber.Get()
}

// GetReturnAccountNumberOk returns a tuple with the ReturnAccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetReturnAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnAccountNumber.Get(), o.ReturnAccountNumber.IsSet()
}

// HasReturnAccountNumber returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnAccountNumber() bool {
	if o != nil && o.ReturnAccountNumber.IsSet() {
		return true
	}

	return false
}

// SetReturnAccountNumber gets a reference to the given NullableString and assigns it to the ReturnAccountNumber field.
func (o *ACHResponse) SetReturnAccountNumber(v string) {
	o.ReturnAccountNumber.Set(&v)
}
// SetReturnAccountNumberNil sets the value for ReturnAccountNumber to be an explicit nil
func (o *ACHResponse) SetReturnAccountNumberNil() {
	o.ReturnAccountNumber.Set(nil)
}

// UnsetReturnAccountNumber ensures that no value is present for ReturnAccountNumber, not even an explicit nil
func (o *ACHResponse) UnsetReturnAccountNumber() {
	o.ReturnAccountNumber.Unset()
}

// GetReturnRoutingNumber returns the ReturnRoutingNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetReturnRoutingNumber() string {
	if o == nil || IsNil(o.ReturnRoutingNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnRoutingNumber.Get()
}

// GetReturnRoutingNumberOk returns a tuple with the ReturnRoutingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetReturnRoutingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnRoutingNumber.Get(), o.ReturnRoutingNumber.IsSet()
}

// HasReturnRoutingNumber returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnRoutingNumber() bool {
	if o != nil && o.ReturnRoutingNumber.IsSet() {
		return true
	}

	return false
}

// SetReturnRoutingNumber gets a reference to the given NullableString and assigns it to the ReturnRoutingNumber field.
func (o *ACHResponse) SetReturnRoutingNumber(v string) {
	o.ReturnRoutingNumber.Set(&v)
}
// SetReturnRoutingNumberNil sets the value for ReturnRoutingNumber to be an explicit nil
func (o *ACHResponse) SetReturnRoutingNumberNil() {
	o.ReturnRoutingNumber.Set(nil)
}

// UnsetReturnRoutingNumber ensures that no value is present for ReturnRoutingNumber, not even an explicit nil
func (o *ACHResponse) UnsetReturnRoutingNumber() {
	o.ReturnRoutingNumber.Unset()
}

// GetReturnStatus returns the ReturnStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetReturnStatus() string {
	if o == nil || IsNil(o.ReturnStatus.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnStatus.Get()
}

// GetReturnStatusOk returns a tuple with the ReturnStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetReturnStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnStatus.Get(), o.ReturnStatus.IsSet()
}

// HasReturnStatus returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnStatus() bool {
	if o != nil && o.ReturnStatus.IsSet() {
		return true
	}

	return false
}

// SetReturnStatus gets a reference to the given NullableString and assigns it to the ReturnStatus field.
func (o *ACHResponse) SetReturnStatus(v string) {
	o.ReturnStatus.Set(&v)
}
// SetReturnStatusNil sets the value for ReturnStatus to be an explicit nil
func (o *ACHResponse) SetReturnStatusNil() {
	o.ReturnStatus.Set(nil)
}

// UnsetReturnStatus ensures that no value is present for ReturnStatus, not even an explicit nil
func (o *ACHResponse) UnsetReturnStatus() {
	o.ReturnStatus.Unset()
}

// GetReturnedAt returns the ReturnedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetReturnedAt() string {
	if o == nil || IsNil(o.ReturnedAt.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnedAt.Get()
}

// GetReturnedAtOk returns a tuple with the ReturnedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetReturnedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnedAt.Get(), o.ReturnedAt.IsSet()
}

// HasReturnedAt returns a boolean if a field has been set.
func (o *ACHResponse) HasReturnedAt() bool {
	if o != nil && o.ReturnedAt.IsSet() {
		return true
	}

	return false
}

// SetReturnedAt gets a reference to the given NullableString and assigns it to the ReturnedAt field.
func (o *ACHResponse) SetReturnedAt(v string) {
	o.ReturnedAt.Set(&v)
}
// SetReturnedAtNil sets the value for ReturnedAt to be an explicit nil
func (o *ACHResponse) SetReturnedAtNil() {
	o.ReturnedAt.Set(nil)
}

// UnsetReturnedAt ensures that no value is present for ReturnedAt, not even an explicit nil
func (o *ACHResponse) UnsetReturnedAt() {
	o.ReturnedAt.Unset()
}

// GetSecCode returns the SecCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetSecCode() string {
	if o == nil || IsNil(o.SecCode.Get()) {
		var ret string
		return ret
	}
	return *o.SecCode.Get()
}

// GetSecCodeOk returns a tuple with the SecCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetSecCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecCode.Get(), o.SecCode.IsSet()
}

// HasSecCode returns a boolean if a field has been set.
func (o *ACHResponse) HasSecCode() bool {
	if o != nil && o.SecCode.IsSet() {
		return true
	}

	return false
}

// SetSecCode gets a reference to the given NullableString and assigns it to the SecCode field.
func (o *ACHResponse) SetSecCode(v string) {
	o.SecCode.Set(&v)
}
// SetSecCodeNil sets the value for SecCode to be an explicit nil
func (o *ACHResponse) SetSecCodeNil() {
	o.SecCode.Set(nil)
}

// UnsetSecCode ensures that no value is present for SecCode, not even an explicit nil
func (o *ACHResponse) UnsetSecCode() {
	o.SecCode.Unset()
}

// GetStartedProcessingAt returns the StartedProcessingAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetStartedProcessingAt() string {
	if o == nil || IsNil(o.StartedProcessingAt.Get()) {
		var ret string
		return ret
	}
	return *o.StartedProcessingAt.Get()
}

// GetStartedProcessingAtOk returns a tuple with the StartedProcessingAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetStartedProcessingAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedProcessingAt.Get(), o.StartedProcessingAt.IsSet()
}

// HasStartedProcessingAt returns a boolean if a field has been set.
func (o *ACHResponse) HasStartedProcessingAt() bool {
	if o != nil && o.StartedProcessingAt.IsSet() {
		return true
	}

	return false
}

// SetStartedProcessingAt gets a reference to the given NullableString and assigns it to the StartedProcessingAt field.
func (o *ACHResponse) SetStartedProcessingAt(v string) {
	o.StartedProcessingAt.Set(&v)
}
// SetStartedProcessingAtNil sets the value for StartedProcessingAt to be an explicit nil
func (o *ACHResponse) SetStartedProcessingAtNil() {
	o.StartedProcessingAt.Set(nil)
}

// UnsetStartedProcessingAt ensures that no value is present for StartedProcessingAt, not even an explicit nil
func (o *ACHResponse) UnsetStartedProcessingAt() {
	o.StartedProcessingAt.Unset()
}

// GetSubmittedAt returns the SubmittedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetSubmittedAt() string {
	if o == nil || IsNil(o.SubmittedAt.Get()) {
		var ret string
		return ret
	}
	return *o.SubmittedAt.Get()
}

// GetSubmittedAtOk returns a tuple with the SubmittedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetSubmittedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubmittedAt.Get(), o.SubmittedAt.IsSet()
}

// HasSubmittedAt returns a boolean if a field has been set.
func (o *ACHResponse) HasSubmittedAt() bool {
	if o != nil && o.SubmittedAt.IsSet() {
		return true
	}

	return false
}

// SetSubmittedAt gets a reference to the given NullableString and assigns it to the SubmittedAt field.
func (o *ACHResponse) SetSubmittedAt(v string) {
	o.SubmittedAt.Set(&v)
}
// SetSubmittedAtNil sets the value for SubmittedAt to be an explicit nil
func (o *ACHResponse) SetSubmittedAtNil() {
	o.SubmittedAt.Set(nil)
}

// UnsetSubmittedAt ensures that no value is present for SubmittedAt, not even an explicit nil
func (o *ACHResponse) UnsetSubmittedAt() {
	o.SubmittedAt.Unset()
}

// GetTransactionAmount returns the TransactionAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ACHResponse) GetTransactionAmount() float64 {
	if o == nil || IsNil(o.TransactionAmount.Get()) {
		var ret float64
		return ret
	}
	return *o.TransactionAmount.Get()
}

// GetTransactionAmountOk returns a tuple with the TransactionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ACHResponse) GetTransactionAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionAmount.Get(), o.TransactionAmount.IsSet()
}

// HasTransactionAmount returns a boolean if a field has been set.
func (o *ACHResponse) HasTransactionAmount() bool {
	if o != nil && o.TransactionAmount.IsSet() {
		return true
	}

	return false
}

// SetTransactionAmount gets a reference to the given NullableFloat64 and assigns it to the TransactionAmount field.
func (o *ACHResponse) SetTransactionAmount(v float64) {
	o.TransactionAmount.Set(&v)
}
// SetTransactionAmountNil sets the value for TransactionAmount to be an explicit nil
func (o *ACHResponse) SetTransactionAmountNil() {
	o.TransactionAmount.Set(nil)
}

// UnsetTransactionAmount ensures that no value is present for TransactionAmount, not even an explicit nil
func (o *ACHResponse) UnsetTransactionAmount() {
	o.TransactionAmount.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ACHResponse) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ACHResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ACHResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserGuid returns the UserGuid field value if set, zero value otherwise.
func (o *ACHResponse) GetUserGuid() string {
	if o == nil || IsNil(o.UserGuid) {
		var ret string
		return ret
	}
	return *o.UserGuid
}

// GetUserGuidOk returns a tuple with the UserGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ACHResponse) GetUserGuidOk() (*string, bool) {
	if o == nil || IsNil(o.UserGuid) {
		return nil, false
	}
	return o.UserGuid, true
}

// HasUserGuid returns a boolean if a field has been set.
func (o *ACHResponse) HasUserGuid() bool {
	if o != nil && !IsNil(o.UserGuid) {
		return true
	}

	return false
}

// SetUserGuid gets a reference to the given string and assigns it to the UserGuid field.
func (o *ACHResponse) SetUserGuid(v string) {
	o.UserGuid = &v
}

func (o ACHResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ACHResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountGuid) {
		toSerialize["account_guid"] = o.AccountGuid
	}
	if o.AccountNumberLastFour.IsSet() {
		toSerialize["account_number_last_four"] = o.AccountNumberLastFour.Get()
	}
	if o.AccountType.IsSet() {
		toSerialize["account_type"] = o.AccountType.Get()
	}
	if o.AchInitiatedAt.IsSet() {
		toSerialize["ach_initiated_at"] = o.AchInitiatedAt.Get()
	}
	if !IsNil(o.ClientGuid) {
		toSerialize["client_guid"] = o.ClientGuid
	}
	if o.CorrectedAccountNumber.IsSet() {
		toSerialize["corrected_account_number"] = o.CorrectedAccountNumber.Get()
	}
	if o.CorrectedRoutingNumber.IsSet() {
		toSerialize["corrected_routing_number"] = o.CorrectedRoutingNumber.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstitutionGuid) {
		toSerialize["institution_guid"] = o.InstitutionGuid
	}
	if o.InvestigationNotes.IsSet() {
		toSerialize["investigation_notes"] = o.InvestigationNotes.Get()
	}
	if !IsNil(o.MemberGuid) {
		toSerialize["member_guid"] = o.MemberGuid
	}
	if o.ProcessingErrors.IsSet() {
		toSerialize["processing_errors"] = o.ProcessingErrors.Get()
	}
	if o.ResolutionCode.IsSet() {
		toSerialize["resolution_code"] = o.ResolutionCode.Get()
	}
	if o.ResolutionDetail.IsSet() {
		toSerialize["resolution_detail"] = o.ResolutionDetail.Get()
	}
	if o.ResolvedStatusAt.IsSet() {
		toSerialize["resolved_status_at"] = o.ResolvedStatusAt.Get()
	}
	if !IsNil(o.ReturnCode) {
		toSerialize["return_code"] = o.ReturnCode
	}
	if o.ReturnNotes.IsSet() {
		toSerialize["return_notes"] = o.ReturnNotes.Get()
	}
	if o.ReturnAccountNumber.IsSet() {
		toSerialize["return_account_number"] = o.ReturnAccountNumber.Get()
	}
	if o.ReturnRoutingNumber.IsSet() {
		toSerialize["return_routing_number"] = o.ReturnRoutingNumber.Get()
	}
	if o.ReturnStatus.IsSet() {
		toSerialize["return_status"] = o.ReturnStatus.Get()
	}
	if o.ReturnedAt.IsSet() {
		toSerialize["returned_at"] = o.ReturnedAt.Get()
	}
	if o.SecCode.IsSet() {
		toSerialize["sec_code"] = o.SecCode.Get()
	}
	if o.StartedProcessingAt.IsSet() {
		toSerialize["started_processing_at"] = o.StartedProcessingAt.Get()
	}
	if o.SubmittedAt.IsSet() {
		toSerialize["submitted_at"] = o.SubmittedAt.Get()
	}
	if o.TransactionAmount.IsSet() {
		toSerialize["transaction_amount"] = o.TransactionAmount.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UserGuid) {
		toSerialize["user_guid"] = o.UserGuid
	}
	return toSerialize, nil
}

type NullableACHResponse struct {
	value *ACHResponse
	isSet bool
}

func (v NullableACHResponse) Get() *ACHResponse {
	return v.value
}

func (v *NullableACHResponse) Set(val *ACHResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableACHResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableACHResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableACHResponse(val *ACHResponse) *NullableACHResponse {
	return &NullableACHResponse{value: val, isSet: true}
}

func (v NullableACHResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableACHResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


