/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the UsersResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersResponseBody{}

// UsersResponseBody struct for UsersResponseBody
type UsersResponseBody struct {
	Users []UserResponse `json:"users,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewUsersResponseBody instantiates a new UsersResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersResponseBody() *UsersResponseBody {
	this := UsersResponseBody{}
	return &this
}

// NewUsersResponseBodyWithDefaults instantiates a new UsersResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersResponseBodyWithDefaults() *UsersResponseBody {
	this := UsersResponseBody{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *UsersResponseBody) GetUsers() []UserResponse {
	if o == nil || IsNil(o.Users) {
		var ret []UserResponse
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersResponseBody) GetUsersOk() ([]UserResponse, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *UsersResponseBody) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []UserResponse and assigns it to the Users field.
func (o *UsersResponseBody) SetUsers(v []UserResponse) {
	o.Users = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *UsersResponseBody) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersResponseBody) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *UsersResponseBody) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *UsersResponseBody) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o UsersResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableUsersResponseBody struct {
	value *UsersResponseBody
	isSet bool
}

func (v NullableUsersResponseBody) Get() *UsersResponseBody {
	return v.value
}

func (v *NullableUsersResponseBody) Set(val *UsersResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersResponseBody(val *UsersResponseBody) *NullableUsersResponseBody {
	return &NullableUsersResponseBody{value: val, isSet: true}
}

func (v NullableUsersResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


