/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the ProcessorOwnerBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessorOwnerBody{}

// ProcessorOwnerBody struct for ProcessorOwnerBody
type ProcessorOwnerBody struct {
	AccountOwners []ProcessorOwnerBodyAccountOwnersInner `json:"account_owners,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewProcessorOwnerBody instantiates a new ProcessorOwnerBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessorOwnerBody() *ProcessorOwnerBody {
	this := ProcessorOwnerBody{}
	return &this
}

// NewProcessorOwnerBodyWithDefaults instantiates a new ProcessorOwnerBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessorOwnerBodyWithDefaults() *ProcessorOwnerBody {
	this := ProcessorOwnerBody{}
	return &this
}

// GetAccountOwners returns the AccountOwners field value if set, zero value otherwise.
func (o *ProcessorOwnerBody) GetAccountOwners() []ProcessorOwnerBodyAccountOwnersInner {
	if o == nil || IsNil(o.AccountOwners) {
		var ret []ProcessorOwnerBodyAccountOwnersInner
		return ret
	}
	return o.AccountOwners
}

// GetAccountOwnersOk returns a tuple with the AccountOwners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessorOwnerBody) GetAccountOwnersOk() ([]ProcessorOwnerBodyAccountOwnersInner, bool) {
	if o == nil || IsNil(o.AccountOwners) {
		return nil, false
	}
	return o.AccountOwners, true
}

// HasAccountOwners returns a boolean if a field has been set.
func (o *ProcessorOwnerBody) HasAccountOwners() bool {
	if o != nil && !IsNil(o.AccountOwners) {
		return true
	}

	return false
}

// SetAccountOwners gets a reference to the given []ProcessorOwnerBodyAccountOwnersInner and assigns it to the AccountOwners field.
func (o *ProcessorOwnerBody) SetAccountOwners(v []ProcessorOwnerBodyAccountOwnersInner) {
	o.AccountOwners = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ProcessorOwnerBody) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessorOwnerBody) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ProcessorOwnerBody) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *ProcessorOwnerBody) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o ProcessorOwnerBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessorOwnerBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountOwners) {
		toSerialize["account_owners"] = o.AccountOwners
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableProcessorOwnerBody struct {
	value *ProcessorOwnerBody
	isSet bool
}

func (v NullableProcessorOwnerBody) Get() *ProcessorOwnerBody {
	return v.value
}

func (v *NullableProcessorOwnerBody) Set(val *ProcessorOwnerBody) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessorOwnerBody) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessorOwnerBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessorOwnerBody(val *ProcessorOwnerBody) *NullableProcessorOwnerBody {
	return &NullableProcessorOwnerBody{value: val, isSet: true}
}

func (v NullableProcessorOwnerBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessorOwnerBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


