/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the CategoryUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryUpdateRequest{}

// CategoryUpdateRequest struct for CategoryUpdateRequest
type CategoryUpdateRequest struct {
	Metadata *string `json:"metadata,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewCategoryUpdateRequest instantiates a new CategoryUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryUpdateRequest() *CategoryUpdateRequest {
	this := CategoryUpdateRequest{}
	return &this
}

// NewCategoryUpdateRequestWithDefaults instantiates a new CategoryUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryUpdateRequestWithDefaults() *CategoryUpdateRequest {
	this := CategoryUpdateRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CategoryUpdateRequest) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryUpdateRequest) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CategoryUpdateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *CategoryUpdateRequest) SetMetadata(v string) {
	o.Metadata = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CategoryUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CategoryUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CategoryUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CategoryUpdateRequest) SetName(v string) {
	o.Name = &v
}

func (o CategoryUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCategoryUpdateRequest struct {
	value *CategoryUpdateRequest
	isSet bool
}

func (v NullableCategoryUpdateRequest) Get() *CategoryUpdateRequest {
	return v.value
}

func (v *NullableCategoryUpdateRequest) Set(val *CategoryUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryUpdateRequest(val *CategoryUpdateRequest) *NullableCategoryUpdateRequest {
	return &NullableCategoryUpdateRequest{value: val, isSet: true}
}

func (v NullableCategoryUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


