/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the MicrodepositsResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MicrodepositsResponseBody{}

// MicrodepositsResponseBody struct for MicrodepositsResponseBody
type MicrodepositsResponseBody struct {
	MicroDeposits []MicrodepositResponse `json:"micro_deposits,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewMicrodepositsResponseBody instantiates a new MicrodepositsResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrodepositsResponseBody() *MicrodepositsResponseBody {
	this := MicrodepositsResponseBody{}
	return &this
}

// NewMicrodepositsResponseBodyWithDefaults instantiates a new MicrodepositsResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrodepositsResponseBodyWithDefaults() *MicrodepositsResponseBody {
	this := MicrodepositsResponseBody{}
	return &this
}

// GetMicroDeposits returns the MicroDeposits field value if set, zero value otherwise.
func (o *MicrodepositsResponseBody) GetMicroDeposits() []MicrodepositResponse {
	if o == nil || IsNil(o.MicroDeposits) {
		var ret []MicrodepositResponse
		return ret
	}
	return o.MicroDeposits
}

// GetMicroDepositsOk returns a tuple with the MicroDeposits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrodepositsResponseBody) GetMicroDepositsOk() ([]MicrodepositResponse, bool) {
	if o == nil || IsNil(o.MicroDeposits) {
		return nil, false
	}
	return o.MicroDeposits, true
}

// HasMicroDeposits returns a boolean if a field has been set.
func (o *MicrodepositsResponseBody) HasMicroDeposits() bool {
	if o != nil && !IsNil(o.MicroDeposits) {
		return true
	}

	return false
}

// SetMicroDeposits gets a reference to the given []MicrodepositResponse and assigns it to the MicroDeposits field.
func (o *MicrodepositsResponseBody) SetMicroDeposits(v []MicrodepositResponse) {
	o.MicroDeposits = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *MicrodepositsResponseBody) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrodepositsResponseBody) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *MicrodepositsResponseBody) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *MicrodepositsResponseBody) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o MicrodepositsResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MicrodepositsResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MicroDeposits) {
		toSerialize["micro_deposits"] = o.MicroDeposits
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableMicrodepositsResponseBody struct {
	value *MicrodepositsResponseBody
	isSet bool
}

func (v NullableMicrodepositsResponseBody) Get() *MicrodepositsResponseBody {
	return v.value
}

func (v *NullableMicrodepositsResponseBody) Set(val *MicrodepositsResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrodepositsResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrodepositsResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrodepositsResponseBody(val *MicrodepositsResponseBody) *NullableMicrodepositsResponseBody {
	return &NullableMicrodepositsResponseBody{value: val, isSet: true}
}

func (v NullableMicrodepositsResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrodepositsResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


