/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the AuthorizationCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthorizationCodeResponse{}

// AuthorizationCodeResponse struct for AuthorizationCodeResponse
type AuthorizationCodeResponse struct {
	Code NullableString `json:"code,omitempty"`
}

// NewAuthorizationCodeResponse instantiates a new AuthorizationCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationCodeResponse() *AuthorizationCodeResponse {
	this := AuthorizationCodeResponse{}
	return &this
}

// NewAuthorizationCodeResponseWithDefaults instantiates a new AuthorizationCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationCodeResponseWithDefaults() *AuthorizationCodeResponse {
	this := AuthorizationCodeResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AuthorizationCodeResponse) GetCode() string {
	if o == nil || IsNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthorizationCodeResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *AuthorizationCodeResponse) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *AuthorizationCodeResponse) SetCode(v string) {
	o.Code.Set(&v)
}
// SetCodeNil sets the value for Code to be an explicit nil
func (o *AuthorizationCodeResponse) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *AuthorizationCodeResponse) UnsetCode() {
	o.Code.Unset()
}

func (o AuthorizationCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthorizationCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	return toSerialize, nil
}

type NullableAuthorizationCodeResponse struct {
	value *AuthorizationCodeResponse
	isSet bool
}

func (v NullableAuthorizationCodeResponse) Get() *AuthorizationCodeResponse {
	return v.value
}

func (v *NullableAuthorizationCodeResponse) Set(val *AuthorizationCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationCodeResponse(val *AuthorizationCodeResponse) *NullableAuthorizationCodeResponse {
	return &NullableAuthorizationCodeResponse{value: val, isSet: true}
}

func (v NullableAuthorizationCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


