/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the RepositionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositionRequest{}

// RepositionRequest struct for RepositionRequest
type RepositionRequest struct {
	// The unique identifier for the goal. Defined by MX.
	Guid string `json:"guid"`
	// The priority of the goal in relation to multiple goals.
	Position int32 `json:"position"`
}

// NewRepositionRequest instantiates a new RepositionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositionRequest(guid string, position int32) *RepositionRequest {
	this := RepositionRequest{}
	this.Guid = guid
	this.Position = position
	return &this
}

// NewRepositionRequestWithDefaults instantiates a new RepositionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositionRequestWithDefaults() *RepositionRequest {
	this := RepositionRequest{}
	return &this
}

// GetGuid returns the Guid field value
func (o *RepositionRequest) GetGuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Guid
}

// GetGuidOk returns a tuple with the Guid field value
// and a boolean to check if the value has been set.
func (o *RepositionRequest) GetGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Guid, true
}

// SetGuid sets field value
func (o *RepositionRequest) SetGuid(v string) {
	o.Guid = v
}

// GetPosition returns the Position field value
func (o *RepositionRequest) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *RepositionRequest) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *RepositionRequest) SetPosition(v int32) {
	o.Position = v
}

func (o RepositionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["guid"] = o.Guid
	toSerialize["position"] = o.Position
	return toSerialize, nil
}

type NullableRepositionRequest struct {
	value *RepositionRequest
	isSet bool
}

func (v NullableRepositionRequest) Get() *RepositionRequest {
	return v.value
}

func (v *NullableRepositionRequest) Set(val *RepositionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositionRequest(val *RepositionRequest) *NullableRepositionRequest {
	return &NullableRepositionRequest{value: val, isSet: true}
}

func (v NullableRepositionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


