/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the UpdateGoalRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGoalRequestBody{}

// UpdateGoalRequestBody struct for UpdateGoalRequestBody
type UpdateGoalRequestBody struct {
	Goal *UpdateGoalRequest `json:"goal,omitempty"`
}

// NewUpdateGoalRequestBody instantiates a new UpdateGoalRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGoalRequestBody() *UpdateGoalRequestBody {
	this := UpdateGoalRequestBody{}
	return &this
}

// NewUpdateGoalRequestBodyWithDefaults instantiates a new UpdateGoalRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGoalRequestBodyWithDefaults() *UpdateGoalRequestBody {
	this := UpdateGoalRequestBody{}
	return &this
}

// GetGoal returns the Goal field value if set, zero value otherwise.
func (o *UpdateGoalRequestBody) GetGoal() UpdateGoalRequest {
	if o == nil || IsNil(o.Goal) {
		var ret UpdateGoalRequest
		return ret
	}
	return *o.Goal
}

// GetGoalOk returns a tuple with the Goal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGoalRequestBody) GetGoalOk() (*UpdateGoalRequest, bool) {
	if o == nil || IsNil(o.Goal) {
		return nil, false
	}
	return o.Goal, true
}

// HasGoal returns a boolean if a field has been set.
func (o *UpdateGoalRequestBody) HasGoal() bool {
	if o != nil && !IsNil(o.Goal) {
		return true
	}

	return false
}

// SetGoal gets a reference to the given UpdateGoalRequest and assigns it to the Goal field.
func (o *UpdateGoalRequestBody) SetGoal(v UpdateGoalRequest) {
	o.Goal = &v
}

func (o UpdateGoalRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGoalRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Goal) {
		toSerialize["goal"] = o.Goal
	}
	return toSerialize, nil
}

type NullableUpdateGoalRequestBody struct {
	value *UpdateGoalRequestBody
	isSet bool
}

func (v NullableUpdateGoalRequestBody) Get() *UpdateGoalRequestBody {
	return v.value
}

func (v *NullableUpdateGoalRequestBody) Set(val *UpdateGoalRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGoalRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGoalRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGoalRequestBody(val *UpdateGoalRequestBody) *NullableUpdateGoalRequestBody {
	return &NullableUpdateGoalRequestBody{value: val, isSet: true}
}

func (v NullableUpdateGoalRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGoalRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


