/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the MemberResumeRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberResumeRequestBody{}

// MemberResumeRequestBody struct for MemberResumeRequestBody
type MemberResumeRequestBody struct {
	Member *MemberResumeRequest `json:"member,omitempty"`
}

// NewMemberResumeRequestBody instantiates a new MemberResumeRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberResumeRequestBody() *MemberResumeRequestBody {
	this := MemberResumeRequestBody{}
	return &this
}

// NewMemberResumeRequestBodyWithDefaults instantiates a new MemberResumeRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberResumeRequestBodyWithDefaults() *MemberResumeRequestBody {
	this := MemberResumeRequestBody{}
	return &this
}

// GetMember returns the Member field value if set, zero value otherwise.
func (o *MemberResumeRequestBody) GetMember() MemberResumeRequest {
	if o == nil || IsNil(o.Member) {
		var ret MemberResumeRequest
		return ret
	}
	return *o.Member
}

// GetMemberOk returns a tuple with the Member field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberResumeRequestBody) GetMemberOk() (*MemberResumeRequest, bool) {
	if o == nil || IsNil(o.Member) {
		return nil, false
	}
	return o.Member, true
}

// HasMember returns a boolean if a field has been set.
func (o *MemberResumeRequestBody) HasMember() bool {
	if o != nil && !IsNil(o.Member) {
		return true
	}

	return false
}

// SetMember gets a reference to the given MemberResumeRequest and assigns it to the Member field.
func (o *MemberResumeRequestBody) SetMember(v MemberResumeRequest) {
	o.Member = &v
}

func (o MemberResumeRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberResumeRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Member) {
		toSerialize["member"] = o.Member
	}
	return toSerialize, nil
}

type NullableMemberResumeRequestBody struct {
	value *MemberResumeRequestBody
	isSet bool
}

func (v NullableMemberResumeRequestBody) Get() *MemberResumeRequestBody {
	return v.value
}

func (v *NullableMemberResumeRequestBody) Set(val *MemberResumeRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberResumeRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberResumeRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberResumeRequestBody(val *MemberResumeRequestBody) *NullableMemberResumeRequestBody {
	return &NullableMemberResumeRequestBody{value: val, isSet: true}
}

func (v NullableMemberResumeRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberResumeRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


