/*
MX Platform API

The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

API version: 20111101
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mxplatformgo

import (
	"encoding/json"
)

// checks if the RepeatingTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepeatingTransactionResponse{}

// RepeatingTransactionResponse struct for RepeatingTransactionResponse
type RepeatingTransactionResponse struct {
	AccountGuid NullableString `json:"account_guid,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	Description *string `json:"description,omitempty"`
	Guid *string `json:"guid,omitempty"`
	MemberGuid *string `json:"member_guid,omitempty"`
	MerchantGuid *string `json:"merchant_guid,omitempty"`
	LastPostedDate *string `json:"last_posted_date,omitempty"`
	PredictedOccursOn *string `json:"predicted_occurs_on,omitempty"`
	RecurrenceType *string `json:"recurrence_type,omitempty"`
	UserGuid *string `json:"user_guid,omitempty"`
	RepeatingTransactionType *string `json:"repeating_transaction_type,omitempty"`
	TransactionType *string `json:"transaction_type,omitempty"`
}

// NewRepeatingTransactionResponse instantiates a new RepeatingTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepeatingTransactionResponse() *RepeatingTransactionResponse {
	this := RepeatingTransactionResponse{}
	return &this
}

// NewRepeatingTransactionResponseWithDefaults instantiates a new RepeatingTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepeatingTransactionResponseWithDefaults() *RepeatingTransactionResponse {
	this := RepeatingTransactionResponse{}
	return &this
}

// GetAccountGuid returns the AccountGuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RepeatingTransactionResponse) GetAccountGuid() string {
	if o == nil || IsNil(o.AccountGuid.Get()) {
		var ret string
		return ret
	}
	return *o.AccountGuid.Get()
}

// GetAccountGuidOk returns a tuple with the AccountGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RepeatingTransactionResponse) GetAccountGuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountGuid.Get(), o.AccountGuid.IsSet()
}

// HasAccountGuid returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasAccountGuid() bool {
	if o != nil && o.AccountGuid.IsSet() {
		return true
	}

	return false
}

// SetAccountGuid gets a reference to the given NullableString and assigns it to the AccountGuid field.
func (o *RepeatingTransactionResponse) SetAccountGuid(v string) {
	o.AccountGuid.Set(&v)
}
// SetAccountGuidNil sets the value for AccountGuid to be an explicit nil
func (o *RepeatingTransactionResponse) SetAccountGuidNil() {
	o.AccountGuid.Set(nil)
}

// UnsetAccountGuid ensures that no value is present for AccountGuid, not even an explicit nil
func (o *RepeatingTransactionResponse) UnsetAccountGuid() {
	o.AccountGuid.Unset()
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *RepeatingTransactionResponse) SetAmount(v float32) {
	o.Amount = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RepeatingTransactionResponse) SetDescription(v string) {
	o.Description = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *RepeatingTransactionResponse) SetGuid(v string) {
	o.Guid = &v
}

// GetMemberGuid returns the MemberGuid field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetMemberGuid() string {
	if o == nil || IsNil(o.MemberGuid) {
		var ret string
		return ret
	}
	return *o.MemberGuid
}

// GetMemberGuidOk returns a tuple with the MemberGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetMemberGuidOk() (*string, bool) {
	if o == nil || IsNil(o.MemberGuid) {
		return nil, false
	}
	return o.MemberGuid, true
}

// HasMemberGuid returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasMemberGuid() bool {
	if o != nil && !IsNil(o.MemberGuid) {
		return true
	}

	return false
}

// SetMemberGuid gets a reference to the given string and assigns it to the MemberGuid field.
func (o *RepeatingTransactionResponse) SetMemberGuid(v string) {
	o.MemberGuid = &v
}

// GetMerchantGuid returns the MerchantGuid field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetMerchantGuid() string {
	if o == nil || IsNil(o.MerchantGuid) {
		var ret string
		return ret
	}
	return *o.MerchantGuid
}

// GetMerchantGuidOk returns a tuple with the MerchantGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetMerchantGuidOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantGuid) {
		return nil, false
	}
	return o.MerchantGuid, true
}

// HasMerchantGuid returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasMerchantGuid() bool {
	if o != nil && !IsNil(o.MerchantGuid) {
		return true
	}

	return false
}

// SetMerchantGuid gets a reference to the given string and assigns it to the MerchantGuid field.
func (o *RepeatingTransactionResponse) SetMerchantGuid(v string) {
	o.MerchantGuid = &v
}

// GetLastPostedDate returns the LastPostedDate field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetLastPostedDate() string {
	if o == nil || IsNil(o.LastPostedDate) {
		var ret string
		return ret
	}
	return *o.LastPostedDate
}

// GetLastPostedDateOk returns a tuple with the LastPostedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetLastPostedDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastPostedDate) {
		return nil, false
	}
	return o.LastPostedDate, true
}

// HasLastPostedDate returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasLastPostedDate() bool {
	if o != nil && !IsNil(o.LastPostedDate) {
		return true
	}

	return false
}

// SetLastPostedDate gets a reference to the given string and assigns it to the LastPostedDate field.
func (o *RepeatingTransactionResponse) SetLastPostedDate(v string) {
	o.LastPostedDate = &v
}

// GetPredictedOccursOn returns the PredictedOccursOn field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetPredictedOccursOn() string {
	if o == nil || IsNil(o.PredictedOccursOn) {
		var ret string
		return ret
	}
	return *o.PredictedOccursOn
}

// GetPredictedOccursOnOk returns a tuple with the PredictedOccursOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetPredictedOccursOnOk() (*string, bool) {
	if o == nil || IsNil(o.PredictedOccursOn) {
		return nil, false
	}
	return o.PredictedOccursOn, true
}

// HasPredictedOccursOn returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasPredictedOccursOn() bool {
	if o != nil && !IsNil(o.PredictedOccursOn) {
		return true
	}

	return false
}

// SetPredictedOccursOn gets a reference to the given string and assigns it to the PredictedOccursOn field.
func (o *RepeatingTransactionResponse) SetPredictedOccursOn(v string) {
	o.PredictedOccursOn = &v
}

// GetRecurrenceType returns the RecurrenceType field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetRecurrenceType() string {
	if o == nil || IsNil(o.RecurrenceType) {
		var ret string
		return ret
	}
	return *o.RecurrenceType
}

// GetRecurrenceTypeOk returns a tuple with the RecurrenceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetRecurrenceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RecurrenceType) {
		return nil, false
	}
	return o.RecurrenceType, true
}

// HasRecurrenceType returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasRecurrenceType() bool {
	if o != nil && !IsNil(o.RecurrenceType) {
		return true
	}

	return false
}

// SetRecurrenceType gets a reference to the given string and assigns it to the RecurrenceType field.
func (o *RepeatingTransactionResponse) SetRecurrenceType(v string) {
	o.RecurrenceType = &v
}

// GetUserGuid returns the UserGuid field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetUserGuid() string {
	if o == nil || IsNil(o.UserGuid) {
		var ret string
		return ret
	}
	return *o.UserGuid
}

// GetUserGuidOk returns a tuple with the UserGuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetUserGuidOk() (*string, bool) {
	if o == nil || IsNil(o.UserGuid) {
		return nil, false
	}
	return o.UserGuid, true
}

// HasUserGuid returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasUserGuid() bool {
	if o != nil && !IsNil(o.UserGuid) {
		return true
	}

	return false
}

// SetUserGuid gets a reference to the given string and assigns it to the UserGuid field.
func (o *RepeatingTransactionResponse) SetUserGuid(v string) {
	o.UserGuid = &v
}

// GetRepeatingTransactionType returns the RepeatingTransactionType field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetRepeatingTransactionType() string {
	if o == nil || IsNil(o.RepeatingTransactionType) {
		var ret string
		return ret
	}
	return *o.RepeatingTransactionType
}

// GetRepeatingTransactionTypeOk returns a tuple with the RepeatingTransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetRepeatingTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RepeatingTransactionType) {
		return nil, false
	}
	return o.RepeatingTransactionType, true
}

// HasRepeatingTransactionType returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasRepeatingTransactionType() bool {
	if o != nil && !IsNil(o.RepeatingTransactionType) {
		return true
	}

	return false
}

// SetRepeatingTransactionType gets a reference to the given string and assigns it to the RepeatingTransactionType field.
func (o *RepeatingTransactionResponse) SetRepeatingTransactionType(v string) {
	o.RepeatingTransactionType = &v
}

// GetTransactionType returns the TransactionType field value if set, zero value otherwise.
func (o *RepeatingTransactionResponse) GetTransactionType() string {
	if o == nil || IsNil(o.TransactionType) {
		var ret string
		return ret
	}
	return *o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepeatingTransactionResponse) GetTransactionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionType) {
		return nil, false
	}
	return o.TransactionType, true
}

// HasTransactionType returns a boolean if a field has been set.
func (o *RepeatingTransactionResponse) HasTransactionType() bool {
	if o != nil && !IsNil(o.TransactionType) {
		return true
	}

	return false
}

// SetTransactionType gets a reference to the given string and assigns it to the TransactionType field.
func (o *RepeatingTransactionResponse) SetTransactionType(v string) {
	o.TransactionType = &v
}

func (o RepeatingTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepeatingTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountGuid.IsSet() {
		toSerialize["account_guid"] = o.AccountGuid.Get()
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.MemberGuid) {
		toSerialize["member_guid"] = o.MemberGuid
	}
	if !IsNil(o.MerchantGuid) {
		toSerialize["merchant_guid"] = o.MerchantGuid
	}
	if !IsNil(o.LastPostedDate) {
		toSerialize["last_posted_date"] = o.LastPostedDate
	}
	if !IsNil(o.PredictedOccursOn) {
		toSerialize["predicted_occurs_on"] = o.PredictedOccursOn
	}
	if !IsNil(o.RecurrenceType) {
		toSerialize["recurrence_type"] = o.RecurrenceType
	}
	if !IsNil(o.UserGuid) {
		toSerialize["user_guid"] = o.UserGuid
	}
	if !IsNil(o.RepeatingTransactionType) {
		toSerialize["repeating_transaction_type"] = o.RepeatingTransactionType
	}
	if !IsNil(o.TransactionType) {
		toSerialize["transaction_type"] = o.TransactionType
	}
	return toSerialize, nil
}

type NullableRepeatingTransactionResponse struct {
	value *RepeatingTransactionResponse
	isSet bool
}

func (v NullableRepeatingTransactionResponse) Get() *RepeatingTransactionResponse {
	return v.value
}

func (v *NullableRepeatingTransactionResponse) Set(val *RepeatingTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRepeatingTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRepeatingTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepeatingTransactionResponse(val *RepeatingTransactionResponse) *NullableRepeatingTransactionResponse {
	return &NullableRepeatingTransactionResponse{value: val, isSet: true}
}

func (v NullableRepeatingTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepeatingTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


